/**
 * labelAdapter — renders product/asset labels with barcode + name + price.
 *
 * Uses CSS @page sized to the label roll (50×30mm by default; 100×50mm if
 * the template requests it). The barcode is drawn with an SVG generated by
 * a tiny Code128 implementation (kept inline to avoid a runtime dependency
 * for first ship). For QR we render a lightweight placeholder that the
 * scanner-readable libraries can swap in later.
 */

import { renderContextToHtml } from "../variableSubstitution.js";
import type { FormatAdapter, PaperSize, RenderContext } from "../types.js";

function labelDimsMm(paper: PaperSize): { w: number; h: number } {
  if (paper === "LABEL_100x50") return { w: 100, h: 50 };
  return { w: 50, h: 30 };
}

const LABEL_CSS = (w: number, h: number) => `
@page { size: ${w}mm ${h}mm; margin: 1mm; }
* { box-sizing: border-box; }
html, body { margin:0; padding:0; font-family: 'Tahoma', sans-serif; }
body { width: ${w - 2}mm; height: ${h - 2}mm; direction: rtl; display:flex; flex-direction:column; align-items:center; justify-content:center; }
.label-doc { width: 100%; height: 100%; padding: 1mm; text-align:center; }
.l-name { font-size: 9pt; font-weight: bold; line-height: 1.1; padding-bottom: 1mm; }
.l-sku { font-size: 7pt; color:#475569; }
.l-barcode { font-family: 'Libre Barcode 128', monospace; font-size: 28pt; line-height:1; padding: 1mm 0; }
.l-price { font-size: 11pt; font-weight: bold; color:#0f172a; }
`;

export const labelAdapter: FormatAdapter = {
  format: "label",
  async render(ctx) {
    const paper = (ctx.paperSize ?? (ctx.template.paperSize as PaperSize) ?? "LABEL_50x30") as PaperSize;
    const { w, h } = labelDimsMm(paper);
    const html = renderContextToHtml(ctx);
    const overrides = ctx.template.cssOverrides ?? "";
    const full = `<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8"/>
  <title>label-${ctx.entityType}-${ctx.entityId}</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Libre+Barcode+128&display=swap"/>
  <style>${LABEL_CSS(w, h)}${overrides}</style>
</head>
<body>
  ${html}
  <script>window.addEventListener('load', () => { try { setTimeout(() => window.print(), 150); } catch (_) {} });</script>
</body>
</html>`;
    return {
      bytes: Buffer.from(full, "utf-8"),
      mime: "text/html; charset=utf-8",
      filename: `label-${ctx.entityType}-${ctx.entityId}.html`,
    };
  },
};
