import { lazy } from "react";

// R.1.5 — Finance Dashboard is the new landing page for /finance. The
// chart of accounts stays at /finance/accounts (see the separate route
// entry below). This lets users hit a real overview page instead of
// being dropped into a list view, and demonstrates the unified page
// templates (PageShell, PageStatusBadge, useApiMutation) as a reference
// for the cascade to the rest of the module.
const Dashboard = lazy(() => import("@/pages/finance/dashboard"));
const Accounts = lazy(() => import("@/pages/finance/accounts"));
const AccountsCreate = lazy(() => import("@/pages/create/finance/accounts-create"));
const AccountsEdit = lazy(() => import("@/pages/create/finance/accounts-edit"));
const AccountDetail = lazy(() => import("@/pages/details/account-detail"));
const Vouchers = lazy(() => import("@/pages/finance/vouchers"));
const VouchersCreate = lazy(() => import("@/pages/create/finance/vouchers-create"));
const VoucherDetail = lazy(() => import("@/pages/details/voucher-detail"));
const Journal = lazy(() => import("@/pages/finance/journal"));
const JournalCreate = lazy(() => import("@/pages/create/finance/journal-create"));
const Invoices = lazy(() => import("@/pages/finance/invoices"));
const InvoicesCreate = lazy(() => import("@/pages/create/finance/invoices-create"));
const InvoiceDetail = lazy(() => import("@/pages/finance/invoice-detail"));
const Expenses = lazy(() => import("@/pages/finance/expenses"));
const ExpenseDetail = lazy(() => import("@/pages/details/expense-detail"));
const ExpensesCreate = lazy(() => import("@/pages/create/finance/expenses-create"));
const Budget = lazy(() => import("@/pages/finance/budget"));
const BudgetCreate = lazy(() => import("@/pages/create/finance/budget-create"));
const BudgetDetail = lazy(() => import("@/pages/details/budget-detail"));
const Vendors = lazy(() => import("@/pages/finance/vendors"));
const VendorsCreate = lazy(() => import("@/pages/create/finance/vendors-create"));
const VendorDetail = lazy(() => import("@/pages/finance/vendor-detail"));
const PurchaseOrders = lazy(() => import("@/pages/finance/purchase-orders"));
const PurchaseOrdersCreate = lazy(() => import("@/pages/create/finance/purchase-orders-create"));
const PurchaseOrderDetail = lazy(() => import("@/pages/finance/purchase-order-detail"));
const PaymentRun = lazy(() => import("@/pages/finance/payment-run"));
const FinancialReports = lazy(() => import("@/pages/finance/reports"));
const TaxSystem = lazy(() => import("@/pages/finance/tax-system"));
const Receivables = lazy(() => import("@/pages/finance/receivables"));
const ReceivableDetail = lazy(() => import("@/pages/details/receivable-detail"));
const Payments = lazy(() => import("@/pages/finance/payments-page"));
const Commitments = lazy(() => import("@/pages/finance/commitments"));
const CommitmentDetail = lazy(() => import("@/pages/details/commitment-detail"));
const FinancialRequests = lazy(() => import("@/pages/finance/financial-requests"));
const FinancialRequestDetail = lazy(() => import("@/pages/details/financial-request-detail"));
const Custodies = lazy(() => import("@/pages/finance/custodies"));
const CustodyDetail = lazy(() => import("@/pages/finance/custody-detail"));
const CustodyAgingReport = lazy(() => import("@/pages/finance/custody-aging-report"));
const FiscalPeriods = lazy(() => import("@/pages/finance/fiscal-periods"));
const SalaryAdvances = lazy(() => import("@/pages/finance/salary-advances"));
const SalaryAdvanceDetail = lazy(() => import("@/pages/details/salary-advance-detail"));
const Ledger = lazy(() => import("@/pages/finance/ledger"));
const ArAging = lazy(() => import("@/pages/finance/ar-aging"));
const ApAging = lazy(() => import("@/pages/finance/ap-aging"));
const BankReconciliation = lazy(() => import("@/pages/finance/bank-reconciliation"));
const BankManualMatch = lazy(() => import("@/pages/create/finance/bank-manual-match"));
const FixedAssets = lazy(() => import("@/pages/finance/fixed-assets"));
const FixedAssetDetail = lazy(() => import("@/pages/details/fixed-asset-detail"));
const BatchDepreciate = lazy(() => import("@/pages/create/finance/batch-depreciate"));
const InventoryCosting = lazy(() => import("@/pages/finance/inventory-costing"));
const BankGuarantees = lazy(() => import("@/pages/finance/bank-guarantees"));
const JournalManual = lazy(() => import("@/pages/finance/journal-manual"));
const GLPostingQueue = lazy(() => import("@/pages/finance/gl-posting-queue"));
const JournalManualCreate = lazy(() => import("@/pages/create/finance/journal-manual-create"));
const JournalManualDetail = lazy(() => import("@/pages/finance/journal-manual-detail"));
const Intercompany = lazy(() => import("@/pages/finance/intercompany"));
const IntercompanyConsolidationCreate = lazy(() => import("@/pages/create/finance/intercompany-consolidation-create"));
const CashFlowForecast = lazy(() => import("@/pages/finance/cash-flow-forecast"));
const ProjectCosting = lazy(() => import("@/pages/finance/project-costing"));
const ProjectCostingDetail = lazy(() => import("@/pages/finance/project-costing-detail"));
const CashflowDashboard = lazy(() => import("@/pages/finance/cashflow-dashboard"));
const OpeningBalances = lazy(() => import("@/pages/finance/opening-balances"));
const OpeningBalancesCreate = lazy(() => import("@/pages/create/finance/opening-balances-create"));
const RecurringJournals = lazy(() => import("@/pages/finance/recurring-journals"));
const RecurringJournalsCreate = lazy(() => import("@/pages/create/finance/recurring-journals-create"));
const RecurringJournalDetail = lazy(() => import("@/pages/finance/recurring-journal-detail"));
const YearEndClose = lazy(() => import("@/pages/finance/year-end-close"));
const Treasury = lazy(() => import("@/pages/finance/treasury"));

export const financeRoutes = [
  // /finance → the new dashboard (R.1.5). The chart of accounts moves
  // to its own explicit path so the two pages don't share a URL.
  { path: "/finance", component: Dashboard },
  { path: "/finance/accounts", component: Accounts },
  { path: "/finance/accounts/create", component: AccountsCreate },
  { path: "/finance/accounts/:id/edit", component: AccountsEdit },
  { path: "/finance/accounts/:id", component: AccountDetail },
  { path: "/finance/vouchers", component: Vouchers },
  { path: "/finance/vouchers/create", component: VouchersCreate },
  { path: "/finance/vouchers/:id", component: VoucherDetail },
  { path: "/finance/journal", component: Journal },
  { path: "/finance/journal/create", component: JournalCreate },
  { path: "/finance/invoices", component: Invoices },
  { path: "/finance/invoices/create", component: InvoicesCreate },
  { path: "/finance/invoices/:id", component: InvoiceDetail },
  { path: "/finance/expenses", component: Expenses },
  { path: "/finance/expenses/create", component: ExpensesCreate },
  { path: "/finance/expenses/:id", component: ExpenseDetail },
  { path: "/finance/budget", component: Budget },
  { path: "/finance/budget/create", component: BudgetCreate },
  { path: "/finance/budget/:id", component: BudgetDetail },
  { path: "/finance/vendors", component: Vendors },
  { path: "/finance/vendors/create", component: VendorsCreate },
  { path: "/finance/vendors/:id", component: VendorDetail, subKey: "vendors" },
  { path: "/finance/purchase-orders", component: PurchaseOrders },
  { path: "/finance/purchase-orders/create", component: PurchaseOrdersCreate },
  { path: "/finance/payment-run", component: PaymentRun },
  { path: "/finance/purchase-orders/:id", component: PurchaseOrderDetail },
  { path: "/finance/reports", component: FinancialReports },
  { path: "/finance/tax", component: TaxSystem },
  { path: "/finance/receivables", component: Receivables },
  { path: "/finance/receivables/:id", component: ReceivableDetail },
  { path: "/finance/payments", component: Payments },
  { path: "/finance/commitments", component: Commitments },
  { path: "/finance/commitments/:id", component: CommitmentDetail },
  { path: "/finance/financial-requests", component: FinancialRequests },
  { path: "/finance/financial-requests/:id", component: FinancialRequestDetail },
  { path: "/finance/custodies", component: Custodies },
  { path: "/finance/custodies/report", component: CustodyAgingReport },
  { path: "/finance/custodies/:id", component: CustodyDetail },
  { path: "/finance/fiscal-periods", component: FiscalPeriods },
  { path: "/finance/salary-advances", component: SalaryAdvances },
  { path: "/finance/salary-advances/:id", component: SalaryAdvanceDetail },
  { path: "/finance/ledger/:code", component: Ledger },
  { path: "/finance/ar-aging", component: ArAging },
  { path: "/finance/ap-aging", component: ApAging },
  { path: "/finance/bank-reconciliation", component: BankReconciliation },
  { path: "/finance/bank-reconciliation/manual-match/:batchId/:rowId", component: BankManualMatch },
  { path: "/finance/fixed-assets", component: FixedAssets },
  { path: "/finance/fixed-assets/batch-depreciate", component: BatchDepreciate },
  { path: "/finance/fixed-assets/:id", component: FixedAssetDetail },
  { path: "/finance/inventory-costing", component: InventoryCosting },
  { path: "/finance/bank-guarantees", component: BankGuarantees },
  { path: "/finance/journal-manual", component: JournalManual },
  { path: "/finance/journal-manual/create", component: JournalManualCreate },
  { path: "/finance/journal-manual/:id", component: JournalManualDetail },
  { path: "/finance/gl-posting-queue", component: GLPostingQueue },
  { path: "/finance/intercompany", component: Intercompany },
  { path: "/finance/intercompany/consolidation/create", component: IntercompanyConsolidationCreate },
  { path: "/finance/cash-flow-forecast", component: CashFlowForecast },
  { path: "/finance/project-costing", component: ProjectCosting },
  { path: "/finance/project-costing/:id", component: ProjectCostingDetail },
  { path: "/finance/cashflow", component: CashflowDashboard },
  { path: "/finance/opening-balances", component: OpeningBalances },
  { path: "/finance/opening-balances/create", component: OpeningBalancesCreate },
  { path: "/finance/recurring-journals", component: RecurringJournals },
  { path: "/finance/recurring-journals/create", component: RecurringJournalsCreate },
  { path: "/finance/recurring-journals/:id", component: RecurringJournalDetail },
  { path: "/finance/year-end-close", component: YearEndClose },
  { path: "/finance/treasury", component: Treasury },
];
