import { Link } from "wouter";
import { useApiQuery, asList } from "@/lib/api";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { PageStatusBadge } from "@/components/page-status-badge";
import { Badge } from "@/components/ui/badge";
import { CheckSquare, Plus } from "lucide-react";
import { formatDateAr } from "@/lib/formatters";

const priorityLabels: Record<string, string> = { high: "عالية", medium: "متوسطة", low: "منخفضة" };
const priorityColors: Record<string, string> = {
  high: "bg-rose-100 text-rose-700",
  medium: "bg-amber-100 text-amber-700",
  low: "bg-emerald-100 text-emerald-700",
};

interface LinkedTasksProps {
  entityType: string;
  entityId: string | number;
  includeMaintenanceTasks?: boolean;
}

export function LinkedTasks({ entityType, entityId }: LinkedTasksProps) {
  const extraParams = entityType === "property-unit" ? "&includeRelatedMaintenance=true" : "";
  const { data: tasksResp, isLoading } = useApiQuery<any>(
    ["linked-tasks", entityType, String(entityId)],
    `/tasks?linkedEntityType=${entityType}&linkedEntityId=${entityId}${extraParams}`,
    !!entityId
  );
  const tasks = asList(tasksResp);

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center gap-2">
            <CheckSquare className="w-5 h-5" /> المهام المرتبطة ({tasks.length})
          </CardTitle>
          <Link href={`/tasks/create?linkedEntityType=${entityType}&linkedEntityId=${entityId}`}>
            <Button size="sm" variant="outline" className="gap-1">
              <Plus className="h-3.5 w-3.5" /> مهمة جديدة
            </Button>
          </Link>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        {isLoading ? (
          <p className="text-center text-gray-400 py-8">جاري التحميل...</p>
        ) : tasks.length === 0 ? (
          <p className="text-center text-gray-400 py-8">لا توجد مهام مرتبطة</p>
        ) : (
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-gray-50">
                <th className="p-3 text-right">العنوان</th>
                <th className="p-3 text-right">الأولوية</th>
                <th className="p-3 text-right">الحالة</th>
                <th className="p-3 text-right">المكلّف</th>
                <th className="p-3 text-right">الموعد</th>
              </tr>
            </thead>
            <tbody>
              {tasks.map((task: any) => (
                <tr key={task.id} className="border-b hover:bg-gray-50">
                  <td className="p-3 font-medium">
                    {task.title}
                    {task.autoGenerated && (
                      <Badge variant="outline" className="ms-2 text-[10px] px-1">تلقائية</Badge>
                    )}
                  </td>
                  <td className="p-3">
                    <Badge className={priorityColors[task.priority] || "bg-gray-100 text-gray-700"}>
                      {priorityLabels[task.priority] || task.priority}
                    </Badge>
                  </td>
                  <td className="p-3"><PageStatusBadge status={task.status} /></td>
                  <td className="p-3 text-gray-500">{task.assigneeName || "-"}</td>
                  <td className="p-3 text-gray-500">
                    {task.scheduledStart
                      ? new Date(task.scheduledStart).toLocaleString("ar-SA", { month: "short", day: "numeric" })
                      : task.scheduledDate
                      ? formatDateAr(task.scheduledDate)
                      : "-"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </CardContent>
    </Card>
  );
}
