ALTER TABLE sms_queue
  ADD COLUMN IF NOT EXISTS "externalId" TEXT,
  ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "attemptCount" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "errorMessage" TEXT,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE whatsapp_queue
  ADD COLUMN IF NOT EXISTS "externalId" TEXT,
  ADD COLUMN IF NOT EXISTS "sentAt" TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS "attemptCount" INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "errorMessage" TEXT,
  ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMPTZ DEFAULT NOW();
