-- Add deletedAt columns for soft-delete support across all modules
-- Required by Task #105 and #106 which added deletedAt IS NULL filters

ALTER TABLE clients ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE crm_opportunities ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE fleet_vehicles ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE fleet_trips ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE fleet_maintenance ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE fleet_fuel_logs ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE fleet_insurance ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE fleet_drivers ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE legal_contracts ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE legal_cases ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE warehouse_products ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE warehouse_categories ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE property_units ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE property_buildings ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE property_owners ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE rental_contracts ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE hr_leave_requests ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;
ALTER TABLE ticket_replies ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP WITH TIME ZONE DEFAULT NULL;

-- Add missing columns for chart_of_accounts (required by finance-journal voucher validation)
ALTER TABLE chart_of_accounts ADD COLUMN IF NOT EXISTS subtype VARCHAR DEFAULT NULL;
ALTER TABLE chart_of_accounts ADD COLUMN IF NOT EXISTS "accountSubtype" VARCHAR DEFAULT NULL;
ALTER TABLE chart_of_accounts ADD COLUMN IF NOT EXISTS nature VARCHAR DEFAULT NULL;
