// Applies a validated proposal: dry-run = save to .agent-state/proposed/.
// live = write files locally, run typecheck, then hand to _pr_push.

import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { writeProposed, appendFixLog } from "./lib/state.mjs";

const REPO_ROOT = new URL("../../", import.meta.url).pathname;

export function dryRunApply({ finding, context, proposal }) {
  const slug = `${finding.collector}_${finding.key}`;
  const file = writeProposed(slug, { finding, context: stripContext(context), proposal });
  appendFixLog({ action: "dry-run-proposed", errorKey: finding.key, file, summary: proposal.summary });
  return { mode: "dry-run", proposedFile: file };
}

function stripContext(ctx) {
  // Keep proposal context small in the saved file
  return {
    finding: ctx.finding,
    files: Object.fromEntries(Object.entries(ctx.files || {}).map(([k, v]) => [k, v ? { path: v.path, length: v.content?.length || 0 } : null])),
    liveDb: ctx.liveDb,
    recentMigrations: ctx.recentMigrations,
  };
}

export function liveApply({ finding, proposal, branchPrefix }) {
  // Write files to working tree
  for (const f of proposal.files) {
    const abs = path.join(REPO_ROOT, f.path);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, f.content);
  }

  // Local sanity gate before pushing — typecheck
  const tc = spawnSync("pnpm", ["run", "typecheck:libs"], {
    cwd: REPO_ROOT, encoding: "utf8", timeout: 240_000,
  });
  if (tc.status !== 0) {
    appendFixLog({ action: "typecheck-failed", errorKey: finding.key, stderr: (tc.stderr || tc.stdout || "").slice(-800) });
    // Revert by re-checking out via git is blocked here; rely on guard CI as final gate.
    return { mode: "live", success: false, reason: "typecheck-failed" };
  }

  // Hand off to _pr_push by writing its state file
  const branch = `${branchPrefix}${finding.collector}-${finding.key}-${Date.now().toString(36)}`;
  const pushState = {
    branch,
    title: proposal.prTitle || `fix(self-heal): ${proposal.summary || finding.id}`,
    body: buildPrBody({ finding, proposal }),
    files: proposal.files.map((f) => f.path),
  };
  const stateFile = process.env.PR_PUSH_STATE || "/tmp/_pr_push_state.json";
  fs.writeFileSync(stateFile, JSON.stringify(pushState, null, 2));

  appendFixLog({ action: "pr-push-state-written", errorKey: finding.key, branch, stateFile });
  return { mode: "live", success: true, branch, stateFile };
}

function buildPrBody({ finding, proposal }) {
  return [
    `**Self-Heal automated fix**`,
    ``,
    `**Detector:** ${finding.collector}`,
    `**Drift:** \`${finding.id}\` ${finding.table ? `on table \`${finding.table}\`` : ""} (${finding.kind}) in \`${finding.file}\``,
    ``,
    `**Root cause (model):** ${proposal.rootCause || "(not provided)"}`,
    ``,
    `**Risk level:** ${proposal.riskLevel || "unknown"}`,
    ``,
    `**Summary:** ${proposal.summary || ""}`,
    ``,
    `_Generated by \`scripts/_self_heal_loop.mjs\`. Guard CI is the final gate before merge._`,
  ].join("\n");
}
