// Bridge: registering an obligation also opens a task for the
// responsible department. User asked for this in plain words: "before
// anything expires the system must open a direct task for the
// responsible department".
//
// The obligations engine already tracks the deadline + emits a
// `system.obligation.breached` event when the dueAt passes. But the
// event was a no-op — nobody owned the renewal, no one's task list
// surfaced it, and the cron's escalation never reached a human queue.
//
// This helper closes that loop. For every duration-tracked artefact
// (company document, fleet insurance, employee iqama, bank guarantee,
// contract, smart-expense renewal) we call registerObligationWithTask
// which:
//   1. registers the obligation (same dedupeKey semantics as before)
//   2. inserts a tasks row pre-assigned to:
//        a. the explicit assignedTo if supplied
//        b. the manager of responsibleDepartmentId if it's set
//        c. an unassigned task with `linkedEntityType` so anyone with
//           the matching role can pick it up
//
// Tasks are flagged `autoGenerated=true` and `type='renewal'` so
// they're easy to filter on the operations-center board.

import type { PoolClient } from "pg";
import { rawExecute, rawQuery } from "./rawdb.js";
import { registerObligation, type RegisterObligationInput } from "./obligationsEngine.js";
import { logger } from "./logger.js";

// Mapping of obligation entityType → fallback role_key that picks up
// the task when no department / assignee is supplied. Matches the
// catalog seeded in autoMigrate + migration 249.
const ENTITY_TYPE_TO_ROLE: Record<string, string> = {
  company_document: "hr_manager",
  fleet_vehicle: "fleet_manager",
  fleet_insurance: "fleet_manager",
  fleet_driver: "fleet_manager",
  employee: "hr_manager",
  employee_document: "hr_manager",
  bank_guarantee: "finance_manager",
  legal_contract: "legal_manager",
  rental_contract: "property_manager",
  property_unit: "property_manager",
  expense: "finance_manager",
  invoice: "finance_manager",
};

export interface RegisterWithTaskInput extends RegisterObligationInput {
  // Optional override — if the operator picked a specific department,
  // we'll try to find its manager first.
  responsibleDepartmentId?: number | null;
  // Priority override — defaults to 'high' when daysLeft <= 7, else 'normal'.
  taskPriority?: "low" | "normal" | "high" | "urgent";
}

// Try to find a sensible assignee for the task in this order:
// 1. The explicit assignedTo on the obligation input.
// 2. The manager of the responsibleDepartmentId, if provided.
// 3. Any active employee whose primary assignment role matches the
//    fallback role for this entityType.
// Returns { userId, assignmentId } or { null, null } if nothing matches.
async function resolveAssignee(
  companyId: number,
  input: RegisterWithTaskInput,
): Promise<{ userId: number | null; assignmentId: number | null }> {
  // (1) Explicit
  if (input.assignedTo) {
    const [row] = await rawQuery<{ userId: number | null }>(
      `SELECT u.id AS "userId"
         FROM employee_assignments ea
         LEFT JOIN users u ON u."employeeId" = ea."employeeId"
        WHERE ea.id = $1 AND ea."companyId" = $2 AND ea.status = 'active'
        LIMIT 1`,
      [input.assignedTo, companyId]
    ).catch(() => []);
    return { userId: row?.userId ?? null, assignmentId: input.assignedTo };
  }

  // (2) Department manager
  if (input.responsibleDepartmentId) {
    const [row] = await rawQuery<{ userId: number | null; assignmentId: number | null }>(
      `SELECT u.id AS "userId", ea.id AS "assignmentId"
         FROM departments d
         LEFT JOIN employee_assignments ea ON ea.id = d."managerId"
         LEFT JOIN users u ON u."employeeId" = ea."employeeId"
        WHERE d.id = $1 AND d."companyId" = $2
        LIMIT 1`,
      [input.responsibleDepartmentId, companyId]
    ).catch(() => []);
    if (row?.userId || row?.assignmentId) {
      return { userId: row.userId ?? null, assignmentId: row.assignmentId ?? null };
    }
  }

  // (3) Role-based fallback — find a primary assignment with the role
  // mapped to this entityType. employee_assignments.role is a string
  // (e.g. "fleet_manager") set at employee creation by the resolved
  // effectiveRole logic in routes/employees.ts.
  const roleKey = ENTITY_TYPE_TO_ROLE[input.entityType];
  if (roleKey) {
    const [row] = await rawQuery<{ userId: number | null; assignmentId: number | null }>(
      `SELECT u.id AS "userId", ea.id AS "assignmentId"
         FROM employee_assignments ea
         LEFT JOIN users u ON u."employeeId" = ea."employeeId"
        WHERE ea."companyId" = $1 AND ea.status = 'active' AND ea.role = $2
        ORDER BY ea."isPrimary" DESC NULLS LAST, ea.id ASC
        LIMIT 1`,
      [companyId, roleKey]
    ).catch(() => []);
    if (row?.userId || row?.assignmentId) {
      return { userId: row.userId ?? null, assignmentId: row.assignmentId ?? null };
    }
  }

  return { userId: null, assignmentId: null };
}

function severityToPriority(daysLeft: number): "high" | "normal" {
  return daysLeft <= 7 ? "high" : "normal";
}

// Public API. Registers the obligation AND opens a task. Either may
// fail independently — the helper logs and continues so we never
// block the main create transaction on a notification side-effect.
export async function registerObligationWithTask(
  input: RegisterWithTaskInput,
): Promise<void> {
  // 1. Register the obligation. obligationsEngine already handles
  //    dedupe + table creation lazily.
  try {
    await registerObligation(input);
  } catch (e) {
    logger.warn(e, "[obligation-task-bridge] registerObligation failed");
  }

  // 2. Compute the days-from-now to derive the priority.
  let daysLeft = 30;
  try {
    const due = new Date(input.dueAt);
    daysLeft = Math.round((due.getTime() - Date.now()) / 86_400_000);
  } catch { /* keep default */ }
  const priority = input.taskPriority ?? severityToPriority(daysLeft);

  // 3. Find an assignee.
  const { userId, assignmentId } = await resolveAssignee(input.companyId, input);

  // 4. Open the task. Idempotent via the unique-on-(linkedEntityType,
  //    linkedEntityId, type='renewal') guard below: if a renewal task
  //    already exists for the same entity we silently skip (the
  //    operator can mark the old one done and a new task will open
  //    once the next obligation registration runs).
  try {
    const [existing] = await rawQuery<{ id: number }>(
      `SELECT id FROM tasks
        WHERE "companyId" = $1
          AND "linkedEntityType" = $2
          AND "linkedEntityId" = $3
          AND type = 'renewal'
          AND status IN ('pending', 'in_progress')
          AND "deletedAt" IS NULL
        LIMIT 1`,
      [input.companyId, input.entityType, input.entityId]
    ).catch(() => []);
    if (existing) return; // Already on someone's plate.

    const scheduledDate = new Date(input.dueAt).toISOString().slice(0, 10);
    await rawExecute(
      `INSERT INTO tasks
         ("companyId", "branchId", "assignmentId", "assignedTo",
          title, description, type, priority, status,
          "linkedEntityType", "linkedEntityId", "scheduledDate",
          "autoGenerated")
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,'pending',$9,$10,$11,true)`,
      [
        input.companyId,
        input.branchId ?? null,
        assignmentId,
        userId,
        input.title,
        `تذكير تجديد آلي. ${input.metadata?.documentType ? `النوع: ${input.metadata.documentType}.` : ""} ` +
          `موعد الانتهاء يحلّ خلال ${Math.max(daysLeft, 0)} يوم.`,
        "renewal",
        priority,
        input.entityType,
        input.entityId,
        scheduledDate,
      ]
    );
  } catch (e) {
    logger.warn(e, "[obligation-task-bridge] task INSERT failed");
  }
}
