#!/usr/bin/env bash
# ===========================================================================
# bootstrap-vps.sh — الإعداد الأول لسيرفر الإنتاج (Hostinger KVM VPS / Ubuntu)
# ---------------------------------------------------------------------------
# First-time provisioning for a fresh Ubuntu 22.04/24.04 VPS. Run ONCE as root:
#
#   ssh root@<SERVER_IP>
#   curl -fsSL https://raw.githubusercontent.com/barhom64/ghayth-erp/main/deploy/bootstrap-vps.sh -o bootstrap-vps.sh
#   bash bootstrap-vps.sh
#
# What it does (idempotent — safe to re-run):
#   1. Installs Node 24, pnpm, PM2, nginx, PostgreSQL.
#   2. Creates a dedicated `ghayth` OS user and a `ghayth_erp` database.
#   3. Clones the repo and writes a starter .env (you fill the secrets).
#   4. Installs deps, builds API + frontend, publishes the SPA to nginx.
#   5. Configures nginx as a reverse proxy and starts the API under PM2.
#
# After it finishes: edit ~ghayth/ghayth-erp/.env with real secrets, then run
# deploy/deploy.sh to (re)build and reload. HTTPS is set up separately with
# certbot (instructions printed at the end).
# ===========================================================================
set -euo pipefail

REPO_URL="https://github.com/barhom64/ghayth-erp.git"
APP_USER="ghayth"
APP_HOME="/home/${APP_USER}"
APP_DIR="${APP_HOME}/ghayth-erp"
WEB_ROOT="/var/www/ghayth"
DB_NAME="ghayth_erp"
DB_USER="ghayth"
API_PORT="8080"

log() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }

if [[ $EUID -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

# --- 1. System packages ----------------------------------------------------
log "Installing Node 24, nginx, PostgreSQL…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl ca-certificates gnupg git nginx postgresql postgresql-contrib rsync gettext-base
if ! command -v node >/dev/null 2>&1 || [[ "$(node -v | cut -dv -f2 | cut -d. -f1)" -lt 24 ]]; then
  curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
  apt-get install -y nodejs
fi
corepack enable
corepack prepare pnpm@latest --activate
npm install -g pm2

# --- 2. App user -----------------------------------------------------------
log "Ensuring app user '${APP_USER}'…"
id -u "${APP_USER}" >/dev/null 2>&1 || useradd -m -s /bin/bash "${APP_USER}"

# --- 3. PostgreSQL role + database ----------------------------------------
log "Provisioning PostgreSQL database '${DB_NAME}'…"
# Reuse the DB password already stored in .env on re-runs so the role and the
# app stay in sync; only generate a fresh one on a truly first run. (hex-only,
# so it never contains :, @, or spaces — safe in a URL and in SQL.)
if [[ -f "${APP_DIR}/.env" ]] && grep -q '^DATABASE_URL=' "${APP_DIR}/.env"; then
  DB_PASS="$(sed -n 's#^DATABASE_URL=postgres://[^:]*:\([^@]*\)@.*#\1#p' "${APP_DIR}/.env")"
fi
DB_PASS="${DB_PASS:-$(openssl rand -hex 24)}"
if sudo -u postgres psql -tc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
  sudo -u postgres psql -c "ALTER ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';"
else
  sudo -u postgres psql -c "CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASS}';"
fi
sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 || \
  sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"

# --- 4. Clone repo ---------------------------------------------------------
log "Cloning repository…"
if [[ -d "${APP_DIR}/.git" ]]; then
  sudo -u "${APP_USER}" git -C "${APP_DIR}" pull --ff-only || true
else
  sudo -u "${APP_USER}" git clone "${REPO_URL}" "${APP_DIR}"
fi

# --- 5. Starter .env (only if missing — never overwrite real secrets) ------
ENV_FILE="${APP_DIR}/.env"
if [[ ! -f "${ENV_FILE}" ]]; then
  log "Writing starter .env (fill in the TODO secrets!)…"
  cat > "${ENV_FILE}" <<EOF
NODE_ENV=production
PORT=${API_PORT}
LOG_LEVEL=info

# Auto-provisioned local Postgres (password generated by bootstrap):
DATABASE_URL=postgres://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}

# TODO — generate each with:  openssl rand -hex 32
JWT_SECRET=TODO_openssl_rand_hex_32
FIELD_ENCRYPTION_KEY=TODO_openssl_rand_hex_32
SECRETS_ENCRYPTION_KEY=TODO_openssl_rand_hex_32

# TODO — your real public origin(s), comma-separated, no trailing slash:
CORS_ORIGINS=https://erp.door.sa

# Optional first admin (≥10 chars, upper+lower+digit+symbol):
# ADMIN_EMAIL=
# ADMIN_PASSWORD=
EOF
  chown "${APP_USER}:${APP_USER}" "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
else
  log ".env already exists — leaving it untouched."
fi

# --- 6. nginx site ---------------------------------------------------------
log "Configuring nginx…"
mkdir -p "${WEB_ROOT}"
chown -R "${APP_USER}:www-data" "${WEB_ROOT}"
export API_UPSTREAM="http://127.0.0.1:${API_PORT}"
envsubst '${API_UPSTREAM}' < "${APP_DIR}/deploy/nginx.conf.template" \
  | sed "s#/usr/share/nginx/html#${WEB_ROOT}#" \
  > /etc/nginx/sites-available/ghayth
ln -sf /etc/nginx/sites-available/ghayth /etc/nginx/sites-enabled/ghayth
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx

# --- 7. First build + start ------------------------------------------------
log "Building and starting the app…"
sudo -u "${APP_USER}" API_PORT="${API_PORT}" WEB_ROOT="${WEB_ROOT}" bash "${APP_DIR}/deploy/deploy.sh" --first-run

# PM2 boot persistence (one-time).
sudo -u "${APP_USER}" pm2 save
env PATH="$PATH:/usr/bin" pm2 startup systemd -u "${APP_USER}" --hp "${APP_HOME}" | tail -1 | bash || true

cat <<DONE

============================================================================
 ✅ Bootstrap complete.

 NEXT STEPS:
   1. Fill the TODO secrets in ${ENV_FILE}
        sudo -u ${APP_USER} nano ${ENV_FILE}
        # generate values with:  openssl rand -hex 32
   2. Apply them and restart:
        sudo -u ${APP_USER} bash ${APP_DIR}/deploy/deploy.sh
   3. Point your domain's DNS A record to this server's IP, then enable HTTPS:
        apt-get install -y certbot python3-certbot-nginx
        certbot --nginx -d erp.door.sa
   4. Open the firewall:
        ufw allow 'Nginx Full' && ufw allow OpenSSH && ufw --force enable

 To update later (after pushing to main): deploy/deploy.sh
============================================================================
DONE
