import { handleRouteError } from "../lib/errorHandler.js";
import { Router } from "express";
import { rawQuery, rawExecute, withTransaction } from "../lib/rawdb.js";
import { hashPassword } from "../lib/auth.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
import { pool } from "../lib/rawdb.js";
import { integrationService } from "../lib/integrationService.js";
import { invalidatePermissionCache } from "../middlewares/permissionMiddleware.js";

const router = Router();
router.use(authMiddleware);

const ADMIN_ROLES = ["owner", "admin", "general_manager"];
const ADMIN_ROLE_LEVEL = 90;

async function requireAdmin(req: any, res: any): Promise<boolean> {
  const scope = req.scope;
  if (!scope) {
    res.status(403).json({ error: "غير مصرح: صلاحيات المسؤول مطلوبة" });
    return false;
  }
  try {
    const rows = await rawQuery<{ level: number }>(
      `SELECT MAX(level) AS level FROM user_roles WHERE "userId" = $1 AND "companyId" = $2`,
      [scope.userId, scope.companyId]
    );
    if (rows.length > 0 && rows[0].level >= ADMIN_ROLE_LEVEL) return true;
  } catch {}
  if (ADMIN_ROLES.includes(scope.role)) return true;
  res.status(403).json({ error: "غير مصرح: صلاحيات المسؤول مطلوبة" });
  return false;
}

async function userBelongsToCompany(userId: number, companyId: number): Promise<boolean> {
  const [row] = await rawQuery(
    `SELECT 1 FROM users u
     INNER JOIN employees e ON e.id = u."employeeId"
     INNER JOIN employee_assignments ea ON ea."employeeId" = e.id
     WHERE u.id = $1 AND ea."companyId" = $2 LIMIT 1`,
    [userId, companyId]
  );
  return !!row;
}

router.get("/users", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const rows = await rawQuery(`
      SELECT DISTINCT u.id, u.email, u.role, u."isActive", u."lastLoginAt", u."createdAt", u."employeeId",
             e.name AS "employeeName", e."empNumber",
             (SELECT COUNT(*) FROM security_log sl WHERE sl."userId" = u.id AND sl.reason = 'auth_failed' AND sl."createdAt" > NOW() - INTERVAL '7 days') AS "failedAttempts7d"
      FROM users u
      LEFT JOIN employees e ON e.id = u."employeeId"
      LEFT JOIN employee_assignments ea ON ea."employeeId" = e.id AND ea."companyId" = $1
      WHERE ea."companyId" = $1
         OR u.id IN (SELECT "userId" FROM user_roles WHERE "companyId" = $1)
      ORDER BY u."createdAt" DESC
    `, [scope.companyId]);
    res.json({ data: rows, total: rows.length, page: 1, pageSize: rows.length });
  } catch (e: any) { console.error("Get users error:", e); handleRouteError(e, res, "خطأ غير متوقع"); }
});

router.post("/users", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { email, role, password, employeeId } = req.body;
    if (!email) { res.status(400).json({ error: "البريد الإلكتروني مطلوب" }); return; }
    if (employeeId) {
      const [empCheck] = await rawQuery(
        `SELECT 1 FROM employee_assignments WHERE "employeeId" = $1 AND "companyId" = $2 LIMIT 1`,
        [employeeId, scope.companyId]
      );
      if (!empCheck) { res.status(403).json({ error: "الموظف لا ينتمي لشركتك" }); return; }
    }
    const isAutoGenerated = !password;
    const tempPassword = password || Math.random().toString(36).slice(-8) + "A1!";
    const hashed = await hashPassword(tempPassword);
    const r = await rawExecute(
      `INSERT INTO users (email, "passwordHash", role, "employeeId", "isActive") VALUES ($1,$2,$3,$4,true)`,
      [email, hashed, role || "employee", employeeId || null]
    );
    const newUserId = r.insertId;
    const assignedRole = role || "employee";
    const roleDef = PREDEFINED_ROLES.find(r => r.roleKey === assignedRole) || { roleKey: assignedRole, label: assignedRole, modules: [], level: 10 };
    const customRoleDef = await rawQuery<any>(
      `SELECT label, level, modules FROM custom_roles WHERE "companyId"=$1 AND "roleKey"=$2 LIMIT 1`,
      [scope.companyId, assignedRole]
    ).then(rows => rows[0]).catch(() => null);
    const finalDef = customRoleDef
      ? { roleKey: assignedRole, label: customRoleDef.label, level: customRoleDef.level, modules: Array.isArray(customRoleDef.modules) ? customRoleDef.modules : JSON.parse(customRoleDef.modules || "[]") }
      : roleDef;
    await rawExecute(
      `INSERT INTO user_roles ("userId","roleKey",label,level,modules,"companyId","createdAt")
       VALUES ($1,$2,$3,$4,$5,$6,NOW())
       ON CONFLICT ("userId","roleKey","companyId") DO UPDATE SET label=EXCLUDED.label, level=EXCLUDED.level, modules=EXCLUDED.modules`,
      [newUserId, finalDef.roleKey, finalDef.label, finalDef.level, JSON.stringify(finalDef.modules), scope.companyId]
    ).catch(() => {});
    if (isAutoGenerated) {
      rawExecute(
        `INSERT INTO email_queue ("companyId","toEmail","recipientName",subject,body,status,"createdAt","refType","refId")
         VALUES ($1,$2,$3,$4,$5,'pending',NOW(),'user',$6)`,
        [
          scope.companyId,
          email,
          email,
          "بيانات الدخول إلى النظام",
          `مرحباً،\n\nتم إنشاء حساب لك في نظام غيث ERP.\n\nالبريد الإلكتروني: ${email}\nكلمة المرور المؤقتة: ${tempPassword}\n\nيرجى تغيير كلمة المرور فور تسجيل الدخول الأول.\n\nهذه الرسالة تلقائية، يرجى عدم الرد عليها.`,
          r.insertId,
        ]
      ).catch((err) => console.error("Failed to queue welcome email:", err));
    }
    res.status(201).json({
      id: r.insertId,
      email,
      role,
      message: isAutoGenerated
        ? "تم إنشاء الحساب. كلمة المرور المؤقتة قُيِّدت في قائمة الإيميلات للإرسال."
        : "تم إنشاء الحساب بنجاح.",
    });
  } catch (e: any) { console.error("Create user error:", e); handleRouteError(e, res, "خطأ غير متوقع"); }
});

router.patch("/users/:id", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);
    const [userBelongs] = await rawQuery(
      `SELECT 1 FROM users u
       LEFT JOIN employees e ON e.id = u."employeeId"
       LEFT JOIN employee_assignments ea ON ea."employeeId" = e.id AND ea."companyId" = $2
       WHERE u.id = $1 AND (
         ea."companyId" = $2
         OR u.id IN (SELECT "userId" FROM user_roles WHERE "companyId" = $2)
       ) LIMIT 1`,
      [id, scope.companyId]
    );
    if (!userBelongs) { res.status(403).json({ error: "المستخدم لا ينتمي لشركتك" }); return; }
    const { isActive, role, employeeId } = req.body;
    if (employeeId) {
      const [empCheck] = await rawQuery(
        `SELECT 1 FROM employee_assignments WHERE "employeeId" = $1 AND "companyId" = $2 LIMIT 1`,
        [employeeId, scope.companyId]
      );
      if (!empCheck) { res.status(403).json({ error: "الموظف لا ينتمي لشركتك" }); return; }
    }
    const sets: string[] = [];
    const params: any[] = [];
    if (isActive !== undefined) { params.push(isActive); sets.push(`"isActive"=$${params.length}`); }
    if (role !== undefined) { params.push(role); sets.push(`role=$${params.length}`); }
    if (employeeId !== undefined) { params.push(employeeId || null); sets.push(`"employeeId"=$${params.length}`); }
    if (!sets.length) { res.status(400).json({ error: "لا توجد بيانات للتحديث" }); return; }
    params.push(id);
    await rawExecute(`UPDATE users SET ${sets.join(",")} WHERE id=$${params.length}`, params);
    if (role !== undefined) {
      const roleDef = PREDEFINED_ROLES.find(r => r.roleKey === role) || { roleKey: role, label: role, modules: [], level: 10 };
      const customRoleDef = await rawQuery<any>(
        `SELECT label, level, modules FROM custom_roles WHERE "companyId"=$1 AND "roleKey"=$2 LIMIT 1`,
        [scope.companyId, role]
      ).then(rows => rows[0]).catch(() => null);
      const finalDef = customRoleDef
        ? { roleKey: role, label: customRoleDef.label, level: customRoleDef.level, modules: Array.isArray(customRoleDef.modules) ? customRoleDef.modules : JSON.parse(customRoleDef.modules || "[]") }
        : roleDef;
      await rawExecute(
        `INSERT INTO user_roles ("userId","roleKey",label,level,modules,"companyId","createdAt")
         VALUES ($1,$2,$3,$4,$5,$6,NOW())
         ON CONFLICT ("userId","roleKey","companyId") DO UPDATE SET label=EXCLUDED.label, level=EXCLUDED.level, modules=EXCLUDED.modules`,
        [id, finalDef.roleKey, finalDef.label, finalDef.level, JSON.stringify(finalDef.modules), scope.companyId]
      ).catch(() => {});
    }
    res.json({ success: true });
  } catch (e: any) { handleRouteError(e, res, "خطأ غير متوقع"); }
});

router.delete("/users/:id", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);
    if (id === scope.userId) { res.status(400).json({ error: "لا يمكنك حذف حسابك الخاص" }); return; }
    const [userBelongs] = await rawQuery(
      `SELECT 1 FROM users u
       LEFT JOIN employees e ON e.id = u."employeeId"
       LEFT JOIN employee_assignments ea ON ea."employeeId" = e.id AND ea."companyId" = $2
       WHERE u.id = $1 AND (
         ea."companyId" = $2
         OR u.id IN (SELECT "userId" FROM user_roles WHERE "companyId" = $2)
       ) LIMIT 1`,
      [id, scope.companyId]
    );
    if (!userBelongs) { res.status(403).json({ error: "المستخدم لا ينتمي لشركتك" }); return; }
    await rawExecute(
      `DELETE FROM user_roles WHERE "userId"=$1 AND "companyId"=$2`,
      [id, scope.companyId]
    );
    await rawExecute(
      `DELETE FROM employee_assignments ea
       USING employees e
       WHERE ea."employeeId" = e.id AND e.id = (SELECT "employeeId" FROM users WHERE id=$1)
         AND ea."companyId"=$2`,
      [id, scope.companyId]
    ).catch(() => {});
    res.json({ success: true, message: "تم إلغاء وصول المستخدم في شركتك" });
  } catch (e: any) { handleRouteError(e, res, "خطأ غير متوقع"); }
});

router.post("/users/:id/reset-password", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);
    const [userBelongs] = await rawQuery(
      `SELECT 1 FROM users u
       LEFT JOIN employees e ON e.id = u."employeeId"
       LEFT JOIN employee_assignments ea ON ea."employeeId" = e.id AND ea."companyId" = $2
       WHERE u.id = $1 AND (
         ea."companyId" = $2
         OR u.id IN (SELECT "userId" FROM user_roles WHERE "companyId" = $2)
       ) LIMIT 1`,
      [id, scope.companyId]
    );
    if (!userBelongs) { res.status(403).json({ error: "المستخدم لا ينتمي لشركتك" }); return; }
    const { newPassword } = req.body;
    if (!newPassword || newPassword.length < 6) { res.status(400).json({ error: "كلمة المرور يجب أن تكون 6 أحرف على الأقل" }); return; }
    const hashed = await hashPassword(newPassword);
    const result = await rawExecute(`UPDATE users SET "passwordHash"=$1 WHERE id=$2`, [hashed, id]);
    if (result.affectedRows === 0) { res.status(404).json({ error: "المستخدم غير موجود" }); return; }
    res.json({ success: true, message: "تم إعادة تعيين كلمة المرور بنجاح" });
  } catch (e: any) { handleRouteError(e, res, "خطأ غير متوقع"); }
});

router.get("/roles", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const rows = await rawQuery(`SELECT * FROM roles ORDER BY name`);
    res.json({ data: rows, total: rows.length, page: 1, pageSize: rows.length });
  } catch (e: any) { console.error("Get roles error:", e); handleRouteError(e, res, "خطأ غير متوقع"); }
});

router.post("/roles", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { roleKey, label, level, modules, permissions: rolePermissions } = req.body;
    if (!roleKey || !label) { res.status(400).json({ error: "roleKey و label مطلوبان" }); return; }
    if (!/^[a-z_]+$/.test(roleKey)) { res.status(400).json({ error: "roleKey يجب أن يحتوي على أحرف إنجليزية صغيرة وشرطات سفلية فقط" }); return; }
    const roleLevel = Math.max(1, Math.min(99, Number(level) || 10));
    const mods = Array.isArray(modules) ? modules : [];
    await withTransaction(async (tx) => {
      await tx.query(
        `INSERT INTO custom_roles ("companyId","roleKey",label,level,modules,"createdBy","createdAt")
         VALUES ($1,$2,$3,$4,$5,$6,NOW())
         ON CONFLICT ("companyId","roleKey") DO UPDATE SET label=EXCLUDED.label, level=EXCLUDED.level, modules=EXCLUDED.modules`,
        [scope.companyId, roleKey, label, roleLevel, JSON.stringify(mods), scope.userId]
      );
      if (Array.isArray(rolePermissions) && rolePermissions.length > 0) {
        await tx.query(
          `DELETE FROM role_permissions WHERE role=$1 AND "companyId"=$2`,
          [roleKey, scope.companyId]
        );
        for (const perm of rolePermissions) {
          await tx.query(
            `INSERT INTO role_permissions (role, permission, "companyId") VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,
            [roleKey, perm, scope.companyId]
          );
        }
      }
    });
    invalidatePermissionCache(roleKey, scope.companyId);
    res.status(201).json({ success: true, roleKey, label, level: roleLevel, modules: mods });
  } catch (e: any) { console.error("Create role error:", e); handleRouteError(e, res, "خطأ غير متوقع"); }
});

const PREDEFINED_ROLES = [
  { roleKey: "owner", label: "مالك النظام", modules: ["home","hr","finance","fleet","property","operations","warehouse","governance","bi","requests","documents","reports","admin","comms","legal","crm","marketing","store","support","settings"], level: 100 },
  { roleKey: "general_manager", label: "مدير عام", modules: ["home","hr","finance","fleet","property","operations","warehouse","governance","bi","requests","documents","reports","comms","legal","crm","marketing","store","support","settings"], level: 90 },
  { roleKey: "hr_manager", label: "مدير الموارد البشرية", modules: ["home","hr","requests","documents","comms"], level: 70 },
  { roleKey: "finance_manager", label: "مدير المالية", modules: ["home","finance","requests","documents","comms"], level: 70 },
  { roleKey: "fleet_manager", label: "مدير الأسطول", modules: ["home","fleet","requests","documents","comms"], level: 70 },
  { roleKey: "property_manager", label: "مدير الأملاك", modules: ["home","property","requests","documents","comms"], level: 70 },
  { roleKey: "projects_manager", label: "مدير المشاريع", modules: ["home","operations","requests","documents","comms"], level: 70 },
  { roleKey: "warehouse_manager", label: "مدير المستودعات", modules: ["home","warehouse","store","requests","documents","comms"], level: 70 },
  { roleKey: "legal_manager", label: "مدير الشؤون القانونية", modules: ["home","legal","governance","requests","documents","comms"], level: 70 },
  { roleKey: "support_manager", label: "مدير الدعم الفني", modules: ["home","support","requests","documents","comms"], level: 70 },
  { roleKey: "crm_manager", label: "مدير المبيعات", modules: ["home","crm","marketing","requests","documents","comms"], level: 70 },
  { roleKey: "bi_manager", label: "مدير ذكاء الأعمال", modules: ["home","bi","reports","requests","documents","comms"], level: 70 },
  { roleKey: "branch_manager", label: "مدير فرع", modules: ["home","hr","finance","requests","documents","comms","support"], level: 60 },
  { roleKey: "employee", label: "موظف", modules: ["home","requests","documents","comms"], level: 10 },
];

router.get("/predefined-roles", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const customRows = await rawQuery<any>(
      `SELECT "roleKey", label, level, modules FROM custom_roles WHERE "companyId"=$1 ORDER BY level DESC`,
      [scope.companyId]
    ).catch(() => [] as any[]);
    const customRoles = customRows.map((r: any) => ({
      roleKey: r.roleKey,
      label: r.label,
      level: r.level,
      modules: (() => {
        let m = typeof r.modules === "string" ? JSON.parse(r.modules || "[]") : r.modules;
        if (m && typeof m === "object" && !Array.isArray(m) && m.all === true) return undefined;
        return Array.isArray(m) ? m : [];
      })(),
      isCustom: true,
    }));
    const existing = new Set(customRoles.map((r: any) => r.roleKey));
    const predefined = PREDEFINED_ROLES.filter(r => !existing.has(r.roleKey));
    res.json({ data: [...customRoles, ...predefined] });
  } catch (err) { handleRouteError(err, res, "Get predefined roles"); }
});

router.get("/user-roles/:userId", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const userId = Number(req.params.userId);
    if (!userId || isNaN(userId)) { res.status(400).json({ error: "معرف غير صالح" }); return; }
    if (!await userBelongsToCompany(userId, scope.companyId)) {
      res.status(403).json({ error: "المستخدم لا ينتمي لشركتك" }); return;
    }
    const rows = await rawQuery(
      `SELECT * FROM user_roles WHERE "userId"=$1 AND "companyId"=$2 ORDER BY level DESC`,
      [userId, scope.companyId]
    );
    res.json({ data: rows });
  } catch (err) { handleRouteError(err, res, "Get user roles"); }
});

router.post("/user-roles", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { userId, roleKey } = req.body;
    if (!userId || !roleKey || typeof userId !== "number") {
      res.status(400).json({ error: "بيانات غير صالحة: userId و roleKey مطلوبان" }); return;
    }
    if (!await userBelongsToCompany(userId, scope.companyId)) {
      res.status(403).json({ error: "المستخدم لا ينتمي لشركتك" }); return;
    }
    let def: { roleKey: string; label: string; modules: string[]; level: number } | undefined = PREDEFINED_ROLES.find(r => r.roleKey === roleKey);
    if (!def) {
      const [customRole] = await rawQuery<any>(
        `SELECT "roleKey", label, modules, level FROM custom_roles WHERE "roleKey"=$1 AND "companyId"=$2 LIMIT 1`,
        [roleKey, scope.companyId]
      ).catch(() => [] as any[]);
      if (customRole) {
        def = {
          roleKey: customRole.roleKey,
          label: customRole.label,
          level: customRole.level,
          modules: Array.isArray(customRole.modules) ? customRole.modules : (typeof customRole.modules === "string" ? JSON.parse(customRole.modules || "[]") : []),
        };
      }
    }
    if (!def) { res.status(400).json({ error: "دور غير معروف" }); return; }
    await rawExecute(
      `INSERT INTO user_roles ("userId", "roleKey", label, modules, level, "companyId") VALUES ($1,$2,$3,$4,$5,$6)
       ON CONFLICT ("userId","roleKey","companyId") DO UPDATE SET label=EXCLUDED.label, modules=EXCLUDED.modules, level=EXCLUDED.level`,
      [userId, def.roleKey, def.label, JSON.stringify(def.modules), def.level, scope.companyId]
    );
    res.status(201).json({ success: true, roleKey: def.roleKey });
  } catch (err) { handleRouteError(err, res, "Assign user role"); }
});

router.delete("/user-roles/:id", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);
    if (!id || isNaN(id)) { res.status(400).json({ error: "معرف غير صالح" }); return; }
    const [roleRecord] = await rawQuery(
      `SELECT id FROM user_roles WHERE id=$1 AND "companyId"=$2 LIMIT 1`,
      [id, scope.companyId]
    );
    if (!roleRecord) { res.status(403).json({ error: "غير مصرح: الدور لا ينتمي لشركتك" }); return; }
    const result = await rawExecute(`DELETE FROM user_roles WHERE id=$1 AND "companyId"=$2`, [id, scope.companyId]);
    if (result.affectedRows === 0) { res.status(404).json({ error: "الدور غير موجود" }); return; }
    res.json({ message: "تم حذف الدور بنجاح" });
  } catch (err) { handleRouteError(err, res, "Delete user role"); }
});

router.get("/integrations", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const rows = await rawQuery(
      `SELECT * FROM integrations WHERE "companyId"=$1 ORDER BY "createdAt" DESC`,
      [scope.companyId]
    );
    res.json({ data: rows, total: rows.length });
  } catch (err) { handleRouteError(err, res, "List integrations"); }
});

router.post("/integrations", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { type, name, config, status, maxRetries } = req.body;
    const r = await rawExecute(
      `INSERT INTO integrations ("companyId",type,name,config,status,"maxRetries")
       VALUES ($1,$2,$3,$4,$5,$6)`,
      [scope.companyId, type, name, JSON.stringify(config || {}), status || "inactive", maxRetries || 3]
    );
    const [row] = await rawQuery(`SELECT * FROM integrations WHERE id=$1`, [r.insertId]);
    res.status(201).json(row);
  } catch (err) { handleRouteError(err, res, "Create integration"); }
});

router.patch("/integrations/:id", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);
    const b = req.body;
    const sets: string[] = [];
    const params: any[] = [];
    if (b.name !== undefined) { params.push(b.name); sets.push(`name=$${params.length}`); }
    if (b.type !== undefined) { params.push(b.type); sets.push(`type=$${params.length}`); }
    if (b.config !== undefined) { params.push(JSON.stringify(b.config)); sets.push(`config=$${params.length}`); }
    if (b.status !== undefined) { params.push(b.status); sets.push(`status=$${params.length}`); }
    if (b.maxRetries !== undefined) { params.push(b.maxRetries); sets.push(`"maxRetries"=$${params.length}`); }
    sets.push(`"updatedAt"=NOW()`);
    if (sets.length === 1) { res.status(400).json({ error: "لا توجد بيانات" }); return; }
    params.push(id); params.push(scope.companyId);
    await rawExecute(
      `UPDATE integrations SET ${sets.join(",")} WHERE id=$${params.length - 1} AND "companyId"=$${params.length}`,
      params
    );
    const [row] = await rawQuery(`SELECT * FROM integrations WHERE id=$1`, [id]);
    res.json(row);
  } catch (err) { handleRouteError(err, res, "Update integration"); }
});

router.delete("/integrations/:id", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const result = await rawExecute(
      `DELETE FROM integrations WHERE id=$1 AND "companyId"=$2`,
      [Number(req.params.id), scope.companyId]
    );
    if (result.affectedRows === 0) { res.status(404).json({ error: "التكامل غير موجود" }); return; }
    res.json({ message: "تم حذف التكامل" });
  } catch (err) { handleRouteError(err, res, "Delete integration"); }
});

router.post("/integrations/:id/test", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const [integration] = await rawQuery<any>(
      `SELECT * FROM integrations WHERE id=$1 AND "companyId"=$2`,
      [Number(req.params.id), scope.companyId]
    );
    if (!integration) { res.status(404).json({ error: "التكامل غير موجود" }); return; }

    const result = await integrationService.send({
      companyId: scope.companyId,
      channel: integration.type,
      recipient: req.body.testRecipient || "test@test.com",
      subject: "اختبار تكامل غيث ERP",
      body: "هذه رسالة اختبار من نظام غيث ERP للتحقق من إعداد التكامل.",
    });

    res.json({ success: result.success, error: result.error, logId: result.logId });
  } catch (err) { handleRouteError(err, res, "Test integration"); }
});

router.get("/integration-logs", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { channel, status, integrationId } = req.query as any;
    const conditions = [`"companyId"=$1`];
    const params: any[] = [scope.companyId];
    if (channel) { params.push(channel); conditions.push(`channel=$${params.length}`); }
    if (status) { params.push(status); conditions.push(`status=$${params.length}`); }
    if (integrationId) { params.push(Number(integrationId)); conditions.push(`"integrationId"=$${params.length}`); }
    const rows = await rawQuery(
      `SELECT * FROM integration_logs WHERE ${conditions.join(" AND ")} ORDER BY "createdAt" DESC LIMIT 200`,
      params
    );
    res.json({ data: rows, total: rows.length });
  } catch (err) { handleRouteError(err, res, "Get integration logs"); }
});

router.post("/integration-logs/retry", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const result = await integrationService.retryFailed(scope.companyId);
    res.json(result);
  } catch (err) { handleRouteError(err, res, "Retry failed integrations"); }
});

router.get("/system-health", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;

    const dbStart = Date.now();
    let dbStatus = "healthy";
    let dbLatency = 0;
    try {
      await pool.query("SELECT 1");
      dbLatency = Date.now() - dbStart;
    } catch {
      dbStatus = "error";
      dbLatency = Date.now() - dbStart;
    }

    const scope = req.scope!;
    const cid = scope.companyId;

    const [cronJobs] = await rawQuery<any>(
      `SELECT
        COUNT(*) as total,
        COUNT(*) FILTER (WHERE "isActive" = true) as active,
        COUNT(*) FILTER (WHERE "lastStatus" = 'failed') as failed
       FROM cron_jobs`
    ).catch(() => [{ total: 0, active: 0, failed: 0 }]);

    const recentCrons = await rawQuery<any>(
      `SELECT name, "lastRunAt", "lastStatus", "lastError", schedule, "isActive"
       FROM cron_jobs ORDER BY "lastRunAt" DESC NULLS LAST LIMIT 20`
    ).catch(() => []);

    const recentCronLogs = await rawQuery<any>(
      `SELECT "jobName", status, duration, result, error, "createdAt"
       FROM cron_logs ORDER BY "createdAt" DESC LIMIT 20`
    ).catch(() => []);

    const recentErrors = await rawQuery<any>(
      `SELECT action, entity, details, "createdAt"
       FROM event_logs WHERE (action LIKE '%error%' OR action LIKE '%failed%')
         AND ("companyId"=$1 OR "companyId" IS NULL)
       ORDER BY "createdAt" DESC LIMIT 20`,
      [cid]
    ).catch(() => []);

    const [failedLogins] = await rawQuery<any>(
      `SELECT COUNT(*) as count FROM event_logs
       WHERE action IN ('login.failed','auth.failed') AND "createdAt" > NOW() - INTERVAL '24 hours'
         AND ("companyId"=$1 OR "companyId" IS NULL)`,
      [cid]
    ).catch(() => [{ count: 0 }]);

    const [userCount] = await rawQuery<any>(`SELECT COUNT(*) as count FROM users`).catch(() => [{ count: 0 }]);
    const [companyCount] = await rawQuery<any>(`SELECT COUNT(*) as count FROM companies`).catch(() => [{ count: 0 }]);
    const [employeeCount] = await rawQuery<any>(
      `SELECT COUNT(*) as count FROM employees WHERE "companyId"=$1`,
      [cid]
    ).catch(() => [{ count: 0 }]);

    let dbSize = "N/A";
    try {
      const [sizeRow] = await rawQuery<any>(`SELECT pg_size_pretty(pg_database_size(current_database())) as size`);
      dbSize = sizeRow?.size || "N/A";
    } catch {}

    let tableCount = 0;
    try {
      const [tc] = await rawQuery<any>(`SELECT COUNT(*) as count FROM information_schema.tables WHERE table_schema='public'`);
      tableCount = Number(tc?.count || 0);
    } catch {}

    const [integrationStats] = await rawQuery<any>(
      `SELECT
        COUNT(*) as total,
        COUNT(*) FILTER (WHERE status = 'active') as active,
        COUNT(*) FILTER (WHERE status = 'error') as errored
       FROM integrations WHERE "companyId"=$1`,
      [cid]
    ).catch(() => [{ total: 0, active: 0, errored: 0 }]);

    const [pendingMessages] = await rawQuery<any>(
      `SELECT COUNT(*) as count FROM integration_logs WHERE status IN ('pending','retrying') AND "companyId"=$1`,
      [cid]
    ).catch(() => [{ count: 0 }]);

    res.json({
      timestamp: new Date().toISOString(),
      uptime: process.uptime(),
      memoryUsage: process.memoryUsage(),
      services: {
        api: { status: "healthy", uptime: process.uptime() },
        database: { status: dbStatus, latency: dbLatency, size: dbSize, tables: tableCount },
        crons: {
          total: Number(cronJobs?.total || 0),
          active: Number(cronJobs?.active || 0),
          failed: Number(cronJobs?.failed || 0),
        },
        integrations: {
          total: Number(integrationStats?.total || 0),
          active: Number(integrationStats?.active || 0),
          errored: Number(integrationStats?.errored || 0),
          pendingMessages: Number(pendingMessages?.count || 0),
        },
      },
      cronJobs: recentCrons,
      recentCronLogs,
      recentErrors,
      security: {
        failedLogins24h: Number(failedLogins?.count || 0),
      },
      counts: {
        users: Number(userCount?.count || 0),
        companies: Number(companyCount?.count || 0),
        employees: Number(employeeCount?.count || 0),
      },
    });
  } catch (err) { handleRouteError(err, res, "System health check"); }
});

router.get("/violations-report", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { type, priority, status, department, from, to } = req.query as any;

    const conditions = [`"companyId"=$1`];
    const params: any[] = [scope.companyId];

    if (type) { params.push(type); conditions.push(`type=$${params.length}`); }
    if (priority) { params.push(priority); conditions.push(`priority=$${params.length}`); }
    if (status) { params.push(status); conditions.push(`status=$${params.length}`); }
    if (department) { params.push(department); conditions.push(`department=$${params.length}`); }
    if (from) { params.push(from); conditions.push(`"auditDate">=$${params.length}::date`); }
    if (to) { params.push(to); conditions.push(`"auditDate"<=$${params.length}::date`); }

    const whereClause = conditions.join(" AND ");

    const violations = await rawQuery(
      `SELECT * FROM audit_violations WHERE ${whereClause} ORDER BY "createdAt" DESC LIMIT 500`,
      params
    );

    const [totalCount] = await rawQuery<any>(
      `SELECT COUNT(*)::int AS count FROM audit_violations WHERE ${whereClause}`,
      params
    );

    const [summary] = await rawQuery<any>(
      `SELECT
         COUNT(*) AS total,
         COUNT(*) FILTER (WHERE status='open') AS open,
         COUNT(*) FILTER (WHERE status='resolved') AS resolved,
         COUNT(*) FILTER (WHERE priority='critical') AS critical,
         COUNT(*) FILTER (WHERE priority='high') AS high,
         COUNT(*) FILTER (WHERE priority='medium') AS medium,
         COUNT(*) FILTER (WHERE priority='low') AS low
       FROM audit_violations WHERE "companyId"=$1 AND "auditDate"=CURRENT_DATE`,
      [scope.companyId]
    );

    const byType = await rawQuery<any>(
      `SELECT type, COUNT(*)::int AS count
       FROM audit_violations WHERE "companyId"=$1 AND status='open'
       GROUP BY type ORDER BY count DESC`,
      [scope.companyId]
    );

    const byDepartment = await rawQuery<any>(
      `SELECT department, COUNT(*)::int AS count
       FROM audit_violations WHERE "companyId"=$1 AND status='open' AND department IS NOT NULL
       GROUP BY department ORDER BY count DESC`,
      [scope.companyId]
    );

    const trend = await rawQuery<any>(
      `SELECT "auditDate"::text AS date, COUNT(*)::int AS count
       FROM audit_violations WHERE "companyId"=$1
         AND "auditDate" >= CURRENT_DATE - INTERVAL '30 days'
       GROUP BY "auditDate" ORDER BY "auditDate"`,
      [scope.companyId]
    );

    res.json({ data: violations, summary, byType, byDepartment, trend, total: totalCount?.count || violations.length });
  } catch (err) { handleRouteError(err, res, "Violations report"); }
});

router.patch("/violations/:id/resolve", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);

    const [existing] = await rawQuery<any>(
      `SELECT * FROM audit_violations WHERE id=$1 AND "companyId"=$2`,
      [id, scope.companyId]
    );
    if (!existing) { res.status(404).json({ error: "المخالفة غير موجودة" }); return; }
    if (existing.status === "resolved") { res.status(400).json({ error: "المخالفة تم حلها مسبقاً" }); return; }

    await rawExecute(
      `UPDATE audit_violations SET status='resolved', "resolvedBy"=$1, "resolvedAt"=NOW() WHERE id=$2`,
      [scope.activeAssignmentId || scope.userId, id]
    );

    const [updated] = await rawQuery(`SELECT * FROM audit_violations WHERE id=$1`, [id]);
    res.json(updated);
  } catch (err) { handleRouteError(err, res, "Resolve violation"); }
});

router.get("/security-log", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { userId, reason, from, to, page = "1", limit: lim = "50" } = req.query as any;
    const pageNum = Math.max(Number(page), 1);
    const pageSize = Math.min(Math.max(Number(lim), 1), 200);
    const offset = (pageNum - 1) * pageSize;

    const conditions = [`sl."companyId" = $1`];
    const params: any[] = [scope.companyId];
    let paramIdx = 2;

    if (userId) { params.push(Number(userId)); conditions.push(`sl."userId" = $${paramIdx++}`); }
    if (reason) { params.push(reason); conditions.push(`sl.reason = $${paramIdx++}`); }
    if (from) { params.push(from); conditions.push(`sl."createdAt" >= $${paramIdx++}::timestamptz`); }
    if (to) { params.push(to); conditions.push(`sl."createdAt" <= $${paramIdx++}::timestamptz`); }

    const whereClause = conditions.join(" AND ");

    params.push(pageSize);
    const limitIdx = paramIdx++;
    params.push(offset);
    const offsetIdx = paramIdx++;

    const rows = await rawQuery<any>(
      `SELECT sl.id, sl."userId", sl."companyId", sl.role, sl.path, sl.method, sl."requiredPerms", sl.reason, sl.ip, sl."createdAt",
              u.email AS "userEmail", e.name AS "userName"
       FROM security_log sl
       LEFT JOIN users u ON u.id = sl."userId"
       LEFT JOIN employees e ON e.id = u."employeeId"
       WHERE ${whereClause}
       ORDER BY sl."createdAt" DESC
       LIMIT $${limitIdx} OFFSET $${offsetIdx}`,
      params
    );

    const countParams = params.slice(0, params.length - 2);
    const [countRow] = await rawQuery<any>(
      `SELECT COUNT(*) AS total FROM security_log sl WHERE ${whereClause}`,
      countParams
    );

    const [summary] = await rawQuery<any>(
      `SELECT
         COUNT(*) AS total,
         COUNT(*) FILTER (WHERE reason = 'permission_denied') AS "permissionDenied",
         COUNT(*) FILTER (WHERE reason IN ('module_access_denied','module_access_denied_no_modules')) AS "moduleDenied",
         COUNT(*) FILTER (WHERE reason = 'insufficient_level') AS "levelDenied",
         COUNT(*) FILTER (WHERE reason = 'role_required') AS "roleRequired",
         COUNT(*) FILTER (WHERE "createdAt" > NOW() - INTERVAL '24 hours') AS "last24h"
       FROM security_log WHERE "companyId" = $1`,
      [scope.companyId]
    );

    res.json({
      data: rows,
      total: Number(countRow?.total ?? 0),
      page: pageNum,
      pageSize,
      summary,
    });
  } catch (err) { handleRouteError(err, res, "Get security log"); }
});

router.get("/role-permissions", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { role } = req.query as any;
    const conditions = [`("companyId" IS NULL OR "companyId" = $1)`];
    const params: any[] = [scope.companyId];
    if (role) { params.push(role); conditions.push(`"role" = $${params.length}`); }
    const rows = await rawQuery<any>(
      `SELECT id, role, permission, "companyId", "createdAt" FROM role_permissions WHERE ${conditions.join(" AND ")} ORDER BY role, permission`,
      params
    );
    res.json({ data: rows, total: rows.length });
  } catch (err) { handleRouteError(err, res, "Get role permissions"); }
});

router.post("/role-permissions", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { role, permission } = req.body as any;
    if (!role || !permission) {
      res.status(400).json({ error: "role و permission مطلوبان" }); return;
    }
    const r = await rawExecute(
      `INSERT INTO role_permissions (role, permission, "companyId") VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,
      [role, permission, scope.companyId]
    );
    invalidatePermissionCache(role, scope.companyId);
    res.status(201).json({ success: true, id: r.insertId, role, permission });
  } catch (err) { handleRouteError(err, res, "Create role permission"); }
});

router.delete("/role-permissions/:id", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const id = Number(req.params.id);
    const result = await rawExecute(
      `DELETE FROM role_permissions WHERE id=$1 AND "companyId"=$2`,
      [id, scope.companyId]
    );
    if (result.affectedRows === 0) { res.status(404).json({ error: "الصلاحية غير موجودة أو غير مصرح بحذفها" }); return; }
    invalidatePermissionCache(undefined, scope.companyId);
    res.json({ message: "تم حذف الصلاحية" });
  } catch (err) { handleRouteError(err, res, "Delete role permission"); }
});

router.put("/role-permissions/bulk", async (req, res) => {
  try {
    if (!await requireAdmin(req, res)) return;
    const scope = req.scope!;
    const { role, permissions } = req.body as { role: string; permissions: string[] };
    if (!role || !Array.isArray(permissions)) {
      res.status(400).json({ error: "role و permissions مطلوبان" }); return;
    }
    await withTransaction(async (tx) => {
      await tx.query(`DELETE FROM role_permissions WHERE role=$1 AND "companyId"=$2`, [role, scope.companyId]);
      if (permissions.length > 0) {
        const valuesSql: string[] = [];
        const params: any[] = [role, scope.companyId];
        for (const perm of permissions) {
          params.push(perm);
          valuesSql.push(`($1, $${params.length}, $2)`);
        }
        await tx.query(
          `INSERT INTO role_permissions (role, permission, "companyId") VALUES ${valuesSql.join(",")} ON CONFLICT DO NOTHING`,
          params
        );
      }
    });
    invalidatePermissionCache(role, scope.companyId);
    res.json({ success: true, role, count: permissions.length });
  } catch (err) { handleRouteError(err, res, "Bulk update role permissions"); }
});

export default router;
