import { handleRouteError, ValidationError, NotFoundError, ConflictError,
  parseId,
  zodParse,
} from "../lib/errorHandler.js";
import { Router } from "express";
import { z } from "zod";
import { rawQuery } from "../lib/rawdb.js";
import { authorize } from "../lib/rbac/authorize.js";
import { buildScopedWhere, parseScopeFilters } from "../lib/scopedQuery.js";
import { loadBalanceAssign } from "../lib/algorithms.js";
import { emitEvent, createAuditLog } from "../lib/businessHelpers.js";
import { logger } from "../lib/logger.js";

const createTaskSchema = z.object({
  title: z.string().min(1, "عنوان المهمة مطلوب"),
  description: z.string().optional().nullable(),
  type: z.string().optional().nullable(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional().default("medium"),
  scheduledStart: z.string().optional().nullable(),
  scheduledEnd: z.string().optional().nullable(),
  scheduledDate: z.string().optional().nullable(),
  clientName: z.string().optional().nullable(),
  clientId: z.coerce.number().optional().nullable(),
  notes: z.string().optional().nullable(),
  assignedTo: z.union([z.string(), z.coerce.number()]).optional().nullable(),
  linkedEntityType: z.string().optional().nullable(),
  linkedEntityId: z.coerce.number().int().positive().optional().nullable(),
  autoGenerated: z.boolean().optional().default(false),
});

const updateTaskSchema = z.object({
  title: z.string().optional(),
  description: z.string().optional().nullable(),
  type: z.string().optional().nullable(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional(),
  status: z.string().optional(),
  scheduledStart: z.string().optional().nullable(),
  scheduledEnd: z.string().optional().nullable(),
  scheduledDate: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
});

const VALID_TASK_TRANSITIONS: Record<string, string[]> = {
  pending: ["in_progress", "cancelled"],
  in_progress: ["completed", "blocked", "cancelled", "pending"],
  blocked: ["in_progress", "cancelled"],
  completed: ["in_progress"],
  cancelled: ["pending"],
};

const router = Router();

router.get("/", authorize({ feature: "tasks", action: "list" }), async (req, res) => {
  try {
    const scope = req.scope!;
    const { status = "", date = "" } = req.query as any;

    const filters = parseScopeFilters(req);
    const { where: baseWhere, params, nextParamIndex } = buildScopedWhere(scope, filters, {
      companyColumn: 't."companyId"',
      branchColumn: 't."branchId"',
      enforceBranchScope: true,
    });
    let where = baseWhere + ` AND t."deletedAt" IS NULL`;
    let paramIdx = nextParamIndex;

    if (status) {
      where += ` AND t.status = $${paramIdx}`;
      params.push(status);
      paramIdx++;
    }

    if (date) {
      where += ` AND t."scheduledDate" = $${paramIdx}`;
      params.push(date);
      paramIdx++;
    }

    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      where += ` AND t."assignedTo" = $${paramIdx}`;
      params.push(scope.activeAssignmentId);
      paramIdx++;
    }

    const { linkedEntityType, linkedEntityId, includeRelatedMaintenance, relatedUnitId } = req.query as any;
    if (linkedEntityType && linkedEntityId && includeRelatedMaintenance === "true" && linkedEntityType === "property_unit") {
      where += ` AND ((t."linkedEntityType" = $${paramIdx} AND t."linkedEntityId" = $${paramIdx + 1}) OR (t."linkedEntityType" = 'maintenance_request' AND t."linkedEntityId" IN (SELECT id FROM maintenance_requests WHERE "unitId" = $${paramIdx + 1} AND "companyId" = $${paramIdx + 2})))`;
      params.push(linkedEntityType, Number(linkedEntityId), scope.companyId);
      paramIdx += 3;
    } else {
      if (linkedEntityType) {
        where += ` AND t."linkedEntityType" = $${paramIdx}`;
        params.push(linkedEntityType);
        paramIdx++;
      }
      if (linkedEntityId) {
        where += ` AND t."linkedEntityId" = $${paramIdx}`;
        params.push(Number(linkedEntityId));
        paramIdx++;
      }
    }
    if (relatedUnitId && linkedEntityType === "maintenance_request") {
      where += ` AND t."linkedEntityId" IN (SELECT mr2.id FROM maintenance_requests mr2 WHERE mr2."unitId" = $${paramIdx} AND mr2."deletedAt" IS NULL)`;
      params.push(Number(relatedUnitId));
      paramIdx++;
    }

    const tasks = await rawQuery<any>(
      `SELECT t.id, t.title, t.description, t.status, t.priority, t.type,
              t."scheduledDate", t."scheduledStart", t."scheduledEnd",
              t."completedAt", t."createdAt", t.notes,
              t."clientId",
              t."linkedEntityType", t."linkedEntityId", t."autoGenerated",
              e.name AS "assigneeName",
              c.name AS "clientName", c.phone AS "clientPhone"
       FROM tasks t
       LEFT JOIN employee_assignments ea ON ea.id = t."assignedTo"
       LEFT JOIN employees e ON e.id = ea."employeeId"
       LEFT JOIN clients c ON c.id = t."clientId" AND c."deletedAt" IS NULL
       WHERE ${where}
       ORDER BY t.priority DESC, t."scheduledDate" ASC NULLS LAST
       LIMIT 500`,
      params
    );

    // Resolve linkedEntityName in bulk: group ids by type, then issue
    // one tenant-scoped query per distinct type (small constant set).
    const idsByType = new Map<string, Set<number>>();
    for (const task of tasks) {
      if (task.linkedEntityType && task.linkedEntityId) {
        if (!idsByType.has(task.linkedEntityType)) idsByType.set(task.linkedEntityType, new Set());
        idsByType.get(task.linkedEntityType)!.add(Number(task.linkedEntityId));
      }
    }
    const bulkQueryMap: Record<string, string> = {
      property_unit: `SELECT id, "unitNumber" AS name FROM property_units WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      vehicle: `SELECT id, COALESCE("plateNumber", make || ' ' || model) AS name FROM fleet_vehicles WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      client: `SELECT id, name FROM clients WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      project: `SELECT id, name FROM projects WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      contract: `SELECT id, COALESCE("contractNumber", 'عقد #' || id) AS name FROM rental_contracts WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      legal_case: `SELECT id, COALESCE(title, "caseNumber", 'قضية #' || id) AS name FROM legal_cases WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      maintenance_request: `SELECT id, COALESCE(description, category, 'طلب #' || id) AS name FROM maintenance_requests WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
    };
    const namesByType = new Map<string, Map<number, string>>();
    await Promise.all(
      Array.from(idsByType.entries()).map(async ([type, idSet]) => {
        const sql = bulkQueryMap[type];
        if (!sql) return;
        try {
          const rows = await rawQuery<{ id: number; name: string }>(sql, [Array.from(idSet), scope.companyId]);
          const map = new Map<number, string>();
          for (const r of rows) map.set(Number(r.id), r.name);
          namesByType.set(type, map);
        } catch (e) { logger.warn(e, "tasks: linked entity table may not exist"); }
      })
    );
    for (const task of tasks) {
      if (task.linkedEntityType && task.linkedEntityId) {
        task.linkedEntityName = namesByType.get(task.linkedEntityType)?.get(Number(task.linkedEntityId)) ?? null;
      }
    }

    res.json(tasks);
  } catch (err) {
    handleRouteError(err, res, "List tasks error:");
  }
});

router.get("/entity-search", authorize({ feature: "tasks", action: "list" }), async (req, res) => {
  try {
    const scope = req.scope!;
    const { type, q } = req.query as any;
    if (!type) { res.json([]); return; }

    const searchMap: Record<string, string> = {
      property_unit: `SELECT id, "unitNumber" AS name FROM property_units WHERE "companyId"=$1 AND "deletedAt" IS NULL AND ("unitNumber" ILIKE $2 OR "buildingName" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      vehicle: `SELECT id, COALESCE("plateNumber", make || ' ' || model) AS name FROM fleet_vehicles WHERE "companyId"=$1 AND "deletedAt" IS NULL AND ("plateNumber" ILIKE $2 OR make ILIKE $2 OR model ILIKE $2) ORDER BY id DESC LIMIT 10`,
      client: `SELECT id, name FROM clients WHERE "companyId"=$1 AND "deletedAt" IS NULL AND (name ILIKE $2 OR phone ILIKE $2) ORDER BY id DESC LIMIT 10`,
      project: `SELECT id, name FROM projects WHERE "companyId"=$1 AND "deletedAt" IS NULL AND name ILIKE $2 ORDER BY id DESC LIMIT 10`,
      contract: `SELECT id, COALESCE("contractNumber", 'عقد #' || id::text) AS name FROM rental_contracts WHERE "companyId"=$1 AND "deletedAt" IS NULL AND ("contractNumber" ILIKE $2 OR "tenantName" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      legal_case: `SELECT id, COALESCE(title, "caseNumber", 'قضية #' || id::text) AS name FROM legal_cases WHERE "companyId"=$1 AND "deletedAt" IS NULL AND (title ILIKE $2 OR "caseNumber" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      maintenance_request: `SELECT id, COALESCE(description, category, 'طلب #' || id) AS name FROM maintenance_requests WHERE "companyId"=$1 AND "deletedAt" IS NULL AND (description ILIKE $2 OR category ILIKE $2) ORDER BY id DESC LIMIT 10`,
    };

    const query = searchMap[type];
    if (!query) { res.json([]); return; }
    const searchTerm = `%${q || ""}%`;
    const results = await rawQuery<any>(query, [scope.companyId, searchTerm]);
    res.json(results);
  } catch (err) {
    handleRouteError(err, res, "Entity search error:");
  }
});

router.get("/:id", authorize({ feature: "tasks", action: "view", resource: { table: "tasks", idParam: "id" } }), async (req, res) => {
  try {
    const scope = req.scope!;
    const id = parseId(req.params.id, "id");
    let scopeCondition = ` AND t."companyId" = $2`;
    const params: any[] = [id, scope.companyId];
    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      scopeCondition += ` AND t."assignedTo" = $3`;
      params.push(scope.activeAssignmentId);
    }
    const rows = await rawQuery<any>(
      `SELECT t.*, e.name AS "assigneeName",
              c.name AS "clientName", c.phone AS "clientPhone"
       FROM tasks t
       LEFT JOIN employee_assignments ea ON ea.id = t."assignedTo"
       LEFT JOIN employees e ON e.id = ea."employeeId"
       LEFT JOIN clients c ON c.id = t."clientId" AND c."deletedAt" IS NULL
       WHERE t.id = $1${scopeCondition} AND t."deletedAt" IS NULL`,
      params
    );
    if (rows.length === 0) { throw new NotFoundError("المهمة غير موجودة"); }
    res.json(rows[0]);
  } catch (err) {
    handleRouteError(err, res, "Get task error:");
  }
});

router.post("/", authorize({ feature: "tasks", action: "create" }), async (req, res) => {
  try {
    const scope = req.scope!;
    const { title, description, type, priority, scheduledStart, scheduledEnd, scheduledDate, clientName, clientId, notes, assignedTo: bodyAssignedTo, linkedEntityType, linkedEntityId, autoGenerated } = zodParse(createTaskSchema.safeParse(req.body));

    if (scheduledStart && scheduledEnd && new Date(scheduledEnd) < new Date(scheduledStart)) {
      throw new ValidationError("تاريخ النهاية قبل تاريخ البداية", {
        field: "scheduledEnd",
        fix: "اختر موعد انتهاء بعد موعد البداية",
      });
    }

    let resolvedClientId = clientId || null;
    if (!resolvedClientId && clientName) {
      const clients = await rawQuery<any>(
        `SELECT id FROM clients WHERE name = $1 AND "companyId" = $2 LIMIT 1`,
        [clientName, scope.companyId]
      );
      if (clients.length > 0) resolvedClientId = clients[0].id;
    }
    if (resolvedClientId) {
      const [c] = await rawQuery<{ id: number }>(
        `SELECT id FROM clients WHERE id = $1 AND "companyId" = $2 LIMIT 1`,
        [Number(resolvedClientId), scope.companyId]
      );
      if (!c) {
        throw new ValidationError(`العميل رقم ${resolvedClientId} غير موجود في هذه الشركة`, {
          field: "clientId",
          fix: "اختر عميلاً مسجّلاً أو اتركه فارغاً",
        });
      }
    }


      let finalAssignedTo = scope.activeAssignmentId;
      if (bodyAssignedTo === "auto") {
        const smartResult = await loadBalanceAssign(scope.companyId, type || "task");
        if (smartResult) finalAssignedTo = smartResult.assignmentId;
      } else if (bodyAssignedTo !== undefined && bodyAssignedTo !== null && String(bodyAssignedTo).trim() !== "") {
        // Accept either a numeric assignmentId or an employee/user display name
        const trimmed = String(bodyAssignedTo).trim();
        const asNumber = Number(trimmed);
        const isInteger = /^-?\d+$/.test(trimmed) && Number.isInteger(asNumber) && asNumber > 0;
        if (isInteger) {
          // Verify the assignment belongs to the caller's company
          const [scopedAssignment] = await rawQuery<{ id: number }>(
            `SELECT id FROM employee_assignments
             WHERE id = $1 AND "companyId" = $2 AND status = 'active'
             LIMIT 1`,
            [asNumber, scope.companyId]
          );
          if (!scopedAssignment) {
            throw new ValidationError(`المسؤول رقم ${asNumber} غير موجود في هذه الشركة`, {
              field: "assignedTo",
              fix: "اختر موظفاً من القائمة أو اترك الحقل فارغاً",
            });
          }
          finalAssignedTo = scopedAssignment.id;
        } else {
          // Resolve by employee name → active assignment in this company
          const resolved = await rawQuery<{ id: number }>(
            `SELECT a.id FROM employee_assignments a
             JOIN employees e ON e.id = a."employeeId"
             WHERE a."companyId" = $1
               AND (e.name = $2 OR e.email = $2)
               AND a.status = 'active'
             ORDER BY a."isPrimary" DESC, a."createdAt" DESC LIMIT 1`,
            [scope.companyId, trimmed]
          );
          if (resolved.length === 0) {
            throw new ValidationError(`الموظف "${trimmed}" غير موجود`, {
              field: "assignedTo",
              fix: "اختر موظفاً من القائمة أو اترك الحقل فارغاً",
            });
          }
          finalAssignedTo = resolved[0].id;
        }
      }
  
    const rows = await rawQuery<any>(
      `INSERT INTO tasks (
        "companyId", "branchId", "assignmentId", "assignedTo",
        title, description, type, priority, status,
        "scheduledStart", "scheduledEnd", "scheduledDate",
        "clientId", notes, "linkedEntityType", "linkedEntityId", "autoGenerated", "createdAt"
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, $10, $11, $12, $13, $14, $15, $16, NOW())
      RETURNING *`,
      [
        scope.companyId, scope.branchId, scope.activeAssignmentId, finalAssignedTo,
        title, description || null, type || "task", priority || "medium",
        scheduledStart || null, scheduledEnd || null,
        scheduledDate || (scheduledStart ? scheduledStart.split("T")[0] : null),
        resolvedClientId, notes || null,
        linkedEntityType || null, linkedEntityId || null, autoGenerated || false,
      ]
    );

    if (!rows[0]) throw new NotFoundError("فشل في إنشاء المهمة");
    createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "create", entity: "tasks", entityId: rows[0].id, after: { title, type: type || "task", priority: priority || "medium", assignedTo: finalAssignedTo } }).catch((e) => logger.error(e, "tasks background task failed"));
    emitEvent({ companyId: scope.companyId, branchId: scope.branchId, userId: scope.userId, action: "task.created", entity: "tasks", entityId: rows[0].id, details: JSON.stringify({ title, type: type || "task", priority: priority || "medium" }) }).catch((e) => logger.error(e, "tasks background task failed"));
    res.status(201).json(rows[0]);
  } catch (err) { handleRouteError(err, res, "Create task error:"); }
});

router.patch("/:id", authorize({ feature: "tasks", action: "update", resource: { table: "tasks", idParam: "id" } }), async (req, res) => {
  try {
    const scope = req.scope!;
    const id = parseId(req.params.id, "id");
    const { title, description, type, priority, status, scheduledStart, scheduledEnd, scheduledDate, notes } = zodParse(updateTaskSchema.safeParse(req.body)) as any;
    const sets: string[] = [];
    const params: any[] = [];
    let idx = 1;

    const addField = (col: string, val: any) => {
      if (val !== undefined) { sets.push(`"${col}" = $${idx}`); params.push(val); idx++; }
    };

    addField("title", title);
    addField("description", description);
    addField("type", type);
    addField("priority", priority);
    addField("status", status);
    addField("scheduledStart", scheduledStart);
    addField("scheduledEnd", scheduledEnd);
    addField("scheduledDate", scheduledDate);
    addField("notes", notes);

    if (status === "completed") {
      sets.push(`"completedAt" = NOW()`);
    }

    if (sets.length === 0) { throw new ValidationError("لا توجد بيانات للتحديث"); }

    let currentStatus: string | undefined;
    if (status) {
      const [current] = await rawQuery<{ status: string }>(
        `SELECT status FROM tasks WHERE id = $1 AND "companyId" = $2 AND "deletedAt" IS NULL`,
        [id, scope.companyId]
      );
      if (!current) throw new NotFoundError("المهمة غير موجودة");
      currentStatus = current.status;
      const allowed = VALID_TASK_TRANSITIONS[currentStatus];
      if (allowed && !allowed.includes(status)) {
        throw new ConflictError(`لا يمكن نقل المهمة من "${currentStatus}" إلى "${status}"`);
      }
    }

    params.push(id);
    let whereClause = `id = $${idx}`;
    idx++;

    params.push(scope.companyId);
    whereClause += ` AND "companyId" = $${idx}`;
    idx++;

    if (currentStatus) {
      params.push(currentStatus);
      whereClause += ` AND status = $${idx}`;
      idx++;
    }

    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      whereClause += ` AND "assignedTo" = $${idx}`;
      params.push(scope.activeAssignmentId);
      idx++;
    }

    const rows = await rawQuery<any>(
      `UPDATE tasks SET ${sets.join(", ")} WHERE ${whereClause} RETURNING *`,
      params
    );

    if (rows.length === 0) { throw new NotFoundError("المهمة غير موجودة"); }

    createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "update", entity: "tasks", entityId: id, after: { title, description, type, priority, status, scheduledStart, scheduledEnd, scheduledDate, notes } }).catch((e) => logger.error(e, "tasks background task failed"));

    if (status) {
      emitEvent({
        companyId: scope.companyId,
        branchId: scope.branchId,
        userId: scope.userId,
        action: `task.${status}`,
        entity: "tasks",
        entityId: id,
        after: {
          status,
          ...(status === "completed" ? { completedAt: rows[0]?.completedAt ?? new Date().toISOString() } : {}),
          assignedTo: rows[0]?.assignedTo ?? null,
          title: rows[0]?.title ?? null,
        },
      }).catch((e) => logger.error(e, "tasks background task failed"));
    } else if (sets.length > 0) {
      emitEvent({
        companyId: scope.companyId,
        branchId: scope.branchId,
        userId: scope.userId,
        action: "task.updated",
        entity: "tasks",
        entityId: id,
        after: { title: rows[0]?.title ?? null },
      }).catch((e) => logger.error(e, "tasks background task failed"));
    }

    res.json(rows[0]);
  } catch (err) {
    handleRouteError(err, res, "Update task error:");
  }
});

router.delete("/:id", authorize({ feature: "tasks", action: "delete", resource: { table: "tasks", idParam: "id" } }), async (req, res) => {
  try {
    const scope = req.scope!;
    const id = parseId(req.params.id, "id");
    const beforeParams: any[] = [id, scope.companyId];
    let beforeWhere = `id = $1 AND "companyId" = $2`;
    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      beforeWhere += ` AND "assignedTo" = $3`;
      beforeParams.push(scope.activeAssignmentId);
    }
    const [before] = await rawQuery<any>(`SELECT * FROM tasks WHERE ${beforeWhere}`, beforeParams);
    if (!before) { throw new NotFoundError("المهمة غير موجودة"); }

    const params: any[] = [id, scope.companyId];
    let whereClause = `id = $1 AND "companyId" = $2`;

    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      whereClause += ` AND "assignedTo" = $3`;
      params.push(scope.activeAssignmentId);
    }

    const rows = await rawQuery<any>(
      `UPDATE tasks SET "deletedAt" = NOW() WHERE ${whereClause} AND "deletedAt" IS NULL RETURNING id`,
      params
    );
    if (rows.length === 0) { throw new NotFoundError("المهمة غير موجودة"); }
    createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "delete", entity: "tasks", entityId: id, before }).catch((e) => logger.error(e, "tasks background task failed"));
    emitEvent({ companyId: scope.companyId, branchId: scope.branchId, userId: scope.userId, action: "task.deleted", entity: "tasks", entityId: id, details: JSON.stringify({ title: before?.title }) }).catch((e) => logger.error(e, "tasks background task failed"));
    res.json({ success: true });
  } catch (err) {
    handleRouteError(err, res, "Delete task error:");
  }
});

export default router;
