import { handleRouteError, ValidationError, NotFoundError, ConflictError,
  parseId,
  zodParse,
} from "../lib/errorHandler.js";
import { Router } from "express";
import { z } from "zod";
import { rawQuery, withTransaction } from "../lib/rawdb.js";
import { authorize, maskFields } from "../lib/rbac/authorize.js";
import { buildScopedWhere, parseScopeFilters } from "../lib/scopedQuery.js";
import { loadBalanceAssign } from "../lib/algorithms.js";
import { emitEvent, createAuditLog } from "../lib/businessHelpers.js";
import { logger } from "../lib/logger.js";

// A single assignee — either a numeric assignment id, an employee/user
// display name string, or the literal "auto" for load-balanced
// auto-assignment. Used inside the new `assignees` array AND the legacy
// `assignedTo` scalar.
const assigneeRefSchema = z.union([z.string(), z.coerce.number()]);

const createTaskSchema = z.object({
  title: z.string().min(1, "عنوان المهمة مطلوب").max(500, "العنوان طويل جدًا"),
  description: z.string().max(5000, "الوصف طويل جدًا").optional().nullable(),
  type: z.string().optional().nullable(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional().default("medium"),
  scheduledStart: z.string().optional().nullable(),
  scheduledEnd: z.string().optional().nullable(),
  scheduledDate: z.string().optional().nullable(),
  clientName: z.string().optional().nullable(),
  clientId: z.coerce.number().optional().nullable(),
  notes: z.string().max(5000, "الملاحظات طويلة جدًا").optional().nullable(),
  // Single-assignee legacy field. The primary owner of the task. If
  // `assignees` is also provided, the first element of `assignees`
  // becomes the primary and `assignedTo` is ignored.
  assignedTo: assigneeRefSchema.optional().nullable(),
  // Multi-assignee (team). The FIRST item is the accountable owner
  // (role='primary' in task_assignees + tasks.assignedTo mirror); the
  // rest are team members. Empty array = no assignment.
  assignees: z.array(assigneeRefSchema).optional(),
  linkedEntityType: z.string().optional().nullable(),
  linkedEntityId: z.coerce.number().int().positive().optional().nullable(),
  autoGenerated: z.boolean().optional().default(false),
});

const updateTaskSchema = z.object({
  title: z.string().max(500, "العنوان طويل جدًا").optional(),
  description: z.string().max(5000, "الوصف طويل جدًا").optional().nullable(),
  type: z.string().optional().nullable(),
  priority: z.enum(["low", "medium", "high", "critical"]).optional(),
  status: z.string().optional(),
  scheduledStart: z.string().optional().nullable(),
  scheduledEnd: z.string().optional().nullable(),
  scheduledDate: z.string().optional().nullable(),
  notes: z.string().max(5000, "الملاحظات طويلة جدًا").optional().nullable(),
  // Reassign primary owner (also overwrites tasks.assignedTo mirror).
  assignedTo: assigneeRefSchema.optional().nullable(),
  // Full replacement of the assignee team. Empty array clears the team.
  // If omitted, the team is left untouched.
  assignees: z.array(assigneeRefSchema).optional(),
});

// Body for /tasks/:id/assignees mutations.
const assigneeMutationSchema = z.object({
  assignmentId: z.coerce.number().int().positive(),
  role: z.enum(["primary", "member"]).optional().default("member"),
});

const VALID_TASK_TRANSITIONS: Record<string, string[]> = {
  pending: ["in_progress", "cancelled"],
  in_progress: ["completed", "blocked", "cancelled", "pending"],
  blocked: ["in_progress", "cancelled"],
  completed: ["in_progress"],
  cancelled: ["pending"],
};

const router = Router();

interface TaskRow {
  id: number;
  companyId: number;
  branchId: number | null;
  assignmentId: number | null;
  assignedTo: number | null;
  title: string;
  description: string | null;
  type: string | null;
  status: string;
  priority: string;
  scheduledStart: string | null;
  scheduledEnd: string | null;
  scheduledDate: string | null;
  completedAt: string | null;
  clientId: number | null;
  notes: string | null;
  linkedEntityType: string | null;
  linkedEntityId: number | null;
  autoGenerated: boolean | null;
  createdAt: string;
  updatedAt: string | null;
  deletedAt: string | null;
  assigneeName?: string | null;
  clientName?: string | null;
  clientPhone?: string | null;
}

interface TaskListRow {
  id: number;
  title: string;
  description: string | null;
  status: string;
  priority: string;
  type: string | null;
  scheduledDate: string | null;
  scheduledStart: string | null;
  scheduledEnd: string | null;
  completedAt: string | null;
  createdAt: string;
  notes: string | null;
  clientId: number | null;
  linkedEntityType: string | null;
  linkedEntityId: number | null;
  autoGenerated: boolean | null;
  assigneeName: string | null;
  clientName: string | null;
  clientPhone: string | null;
  linkedEntityName?: string | null;
}

interface EntitySearchRow {
  id: number;
  name: string;
}

interface IdRow {
  id: number;
}

interface TaskAssigneeRow {
  id: number;
  taskId: number;
  assignmentId: number;
  role: string;
  assignedAt: string;
  assignedBy: number | null;
  removedAt: string | null;
  employeeName?: string | null;
}

/**
 * Resolve a single `assignedTo`-style reference (number id, numeric
 * string, employee name string, or "auto") to a concrete
 * employee_assignments.id scoped to the caller's company. Throws
 * ValidationError when the reference cannot be resolved — callers
 * should let it bubble.
 */
async function resolveAssigneeRef(
  ref: string | number,
  companyId: number,
  taskType: string,
): Promise<number> {
  if (ref === "auto") {
    const smartResult = await loadBalanceAssign(companyId, taskType);
    if (smartResult) return smartResult.assignmentId;
    throw new ValidationError(
      "تعذّر التعيين التلقائي — لا يوجد موظف متاح في هذه الشركة",
      { field: "assignedTo", fix: "اختر موظفاً يدوياً" },
    );
  }
  const trimmed = String(ref).trim();
  const asNumber = Number(trimmed);
  const isInteger = /^-?\d+$/.test(trimmed) && Number.isInteger(asNumber) && asNumber > 0;
  if (isInteger) {
    const [scopedAssignment] = await rawQuery<{ id: number }>(
      `SELECT id FROM employee_assignments
       WHERE id = $1 AND "companyId" = $2 AND status = 'active'
       LIMIT 1`,
      [asNumber, companyId],
    );
    if (!scopedAssignment) {
      throw new ValidationError(`المسؤول رقم ${asNumber} غير موجود في هذه الشركة`, {
        field: "assignedTo",
        fix: "اختر موظفاً من القائمة",
      });
    }
    return scopedAssignment.id;
  }
  const resolved = await rawQuery<{ id: number }>(
    `SELECT a.id FROM employee_assignments a
     JOIN employees e ON e.id = a."employeeId"
     WHERE a."companyId" = $1
       AND (e.name = $2 OR e.email = $2)
       AND a.status = 'active'
     ORDER BY a."isPrimary" DESC, a."createdAt" DESC LIMIT 1`,
    [companyId, trimmed],
  );
  if (resolved.length === 0) {
    throw new ValidationError(`الموظف "${trimmed}" غير موجود`, {
      field: "assignedTo",
      fix: "اختر موظفاً من القائمة",
    });
  }
  return resolved[0].id;
}

/**
 * Fetch the current team for a task (active assignees only) with
 * employee display names. Returns rows ordered with primary first.
 */
async function fetchTaskAssignees(
  taskId: number,
  companyId: number,
): Promise<TaskAssigneeRow[]> {
  return await rawQuery<TaskAssigneeRow>(
    `SELECT ta.id, ta."taskId", ta."assignmentId", ta.role,
            ta."assignedAt", ta."assignedBy", ta."removedAt",
            e.name AS "employeeName"
     FROM task_assignees ta
     LEFT JOIN employee_assignments ea ON ea.id = ta."assignmentId"
     LEFT JOIN employees e ON e.id = ea."employeeId" AND e."deletedAt" IS NULL
     WHERE ta."taskId" = $1 AND ta."companyId" = $2 AND ta."removedAt" IS NULL
     ORDER BY (ta.role = 'primary') DESC, ta."assignedAt" ASC`,
    [taskId, companyId],
  );
}

router.get("/", authorize({ feature: "tasks", action: "list" }), async (req, res) => {
  try {
    const scope = req.scope!;
    const { status = "", date = "", dateFrom = "", dateTo = "" } = req.query as Record<string, string | undefined>;

    const filters = parseScopeFilters(req);
    const { where: baseWhere, params, nextParamIndex } = buildScopedWhere(scope, filters, {
      companyColumn: 't."companyId"',
      branchColumn: 't."branchId"',
      enforceBranchScope: true,
    });
    let where = baseWhere + ` AND t."deletedAt" IS NULL`;
    let paramIdx = nextParamIndex;

    if (status) {
      where += ` AND t.status = $${paramIdx}`;
      params.push(status);
      paramIdx++;
    }

    if (date) {
      where += ` AND t."scheduledDate" = $${paramIdx}`;
      params.push(date);
      paramIdx++;
    }

    // #651 follow-up — normalize to createdAt per PR #653 template (was t."scheduledDate";
    // collided with the legacy `date` param which keeps scheduledDate semantics for the
    // calendar-day exact-match filter used by the today/tomorrow buttons).
    if (dateFrom) {
      where += ` AND t."createdAt" >= $${paramIdx}::timestamptz`;
      params.push(dateFrom);
      paramIdx++;
    }
    if (dateTo) {
      where += ` AND t."createdAt" <= ($${paramIdx}::date + INTERVAL '1 day')`;
      params.push(dateTo);
      paramIdx++;
    }

    if (scope.role === "employee" && !scope.isOwner && scope.activeAssignmentId) {
      // Multi-assignee scope: see tasks where I'm the primary OR a team
      // member. The OR-with-EXISTS pattern stays index-friendly thanks
      // to idx_task_assignees_assignment (companyId, assignmentId).
      where += ` AND (
        t."assignedTo" = $${paramIdx}
        OR EXISTS (
          SELECT 1 FROM task_assignees ta
          WHERE ta."taskId" = t.id AND ta."assignmentId" = $${paramIdx} AND ta."removedAt" IS NULL
        )
      )`;
      params.push(scope.activeAssignmentId);
      paramIdx++;
    }

    const { linkedEntityType, linkedEntityId, includeRelatedMaintenance, relatedUnitId } = req.query as Record<string, string | undefined>;
    if (linkedEntityType && linkedEntityId && includeRelatedMaintenance === "true" && linkedEntityType === "property_unit") {
      where += ` AND ((t."linkedEntityType" = $${paramIdx} AND t."linkedEntityId" = $${paramIdx + 1}) OR (t."linkedEntityType" = 'maintenance_request' AND t."linkedEntityId" IN (SELECT id FROM maintenance_requests WHERE "unitId" = $${paramIdx + 1} AND "companyId" = $${paramIdx + 2})))`;
      params.push(linkedEntityType, Number(linkedEntityId), scope.companyId);
      paramIdx += 3;
    } else {
      if (linkedEntityType) {
        where += ` AND t."linkedEntityType" = $${paramIdx}`;
        params.push(linkedEntityType);
        paramIdx++;
      }
      if (linkedEntityId) {
        where += ` AND t."linkedEntityId" = $${paramIdx}`;
        params.push(Number(linkedEntityId));
        paramIdx++;
      }
    }
    if (relatedUnitId && linkedEntityType === "maintenance_request") {
      where += ` AND t."linkedEntityId" IN (SELECT mr2.id FROM maintenance_requests mr2 WHERE mr2."unitId" = $${paramIdx} AND mr2."deletedAt" IS NULL)`;
      params.push(Number(relatedUnitId));
      paramIdx++;
    }

    // Pre-aggregate task_assignees counts once via CTE — the original
    // correlated subquery (SELECT COUNT(*) ... WHERE taskId = t.id)
    // was N+1: postgres planned one execution per returned task, so
    // 500 tasks == 501 lookups through task_assignees. This CTE scans
    // the junction table once and joins per-task counts back.
    const tasks = await rawQuery<TaskListRow & { creatorName?: string | null; assigneeCount?: number | null; createdBy?: number | null }>(
      `WITH assignee_counts AS (
         SELECT "taskId", COUNT(*) AS "assigneeCount"
         FROM task_assignees
         WHERE "removedAt" IS NULL
         GROUP BY "taskId"
       )
       SELECT t.id, t.title, t.description, t.status, t.priority, t.type,
              t."scheduledDate", t."scheduledStart", t."scheduledEnd",
              t."completedAt", t."createdAt", t.notes,
              t."clientId", t."createdBy",
              t."linkedEntityType", t."linkedEntityId", t."autoGenerated",
              e.name AS "assigneeName",
              creator.name AS "creatorName",
              COALESCE(ac."assigneeCount", 0)::int AS "assigneeCount",
              c.name AS "clientName", c.phone AS "clientPhone"
       FROM tasks t
       LEFT JOIN employee_assignments ea ON ea.id = t."assignedTo"
       LEFT JOIN employees e ON e.id = ea."employeeId" AND e."companyId" = ea."companyId" AND e."deletedAt" IS NULL
       LEFT JOIN employee_assignments cea ON cea.id = t."createdBy"
       LEFT JOIN employees creator ON creator.id = cea."employeeId" AND creator."companyId" = cea."companyId" AND creator."deletedAt" IS NULL
       LEFT JOIN clients c ON c.id = t."clientId" AND c."companyId" = t."companyId" AND c."deletedAt" IS NULL
       LEFT JOIN assignee_counts ac ON ac."taskId" = t.id
       WHERE ${where}
       ORDER BY t.priority DESC, t."scheduledDate" ASC NULLS LAST
       LIMIT 500`,
      params
    );

    // Resolve linkedEntityName in bulk: group ids by type, then issue
    // one tenant-scoped query per distinct type (small constant set).
    const idsByType = new Map<string, Set<number>>();
    for (const task of tasks) {
      if (task.linkedEntityType && task.linkedEntityId) {
        if (!idsByType.has(task.linkedEntityType)) idsByType.set(task.linkedEntityType, new Set());
        idsByType.get(task.linkedEntityType)!.add(Number(task.linkedEntityId));
      }
    }
    const bulkQueryMap: Record<string, string> = {
      property_unit: `SELECT id, "unitNumber" AS name FROM property_units WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      vehicle: `SELECT id, COALESCE("plateNumber", make || ' ' || model) AS name FROM fleet_vehicles WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      client: `SELECT id, name FROM clients WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      project: `SELECT id, name FROM projects WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      contract: `SELECT id, COALESCE("contractNumber", 'عقد #' || id) AS name FROM rental_contracts WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      legal_case: `SELECT id, COALESCE(title, "caseNumber", 'قضية #' || id) AS name FROM legal_cases WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
      maintenance_request: `SELECT id, COALESCE(description, category, 'طلب #' || id) AS name FROM maintenance_requests WHERE id = ANY($1) AND "companyId"=$2 AND "deletedAt" IS NULL`,
    };
    const namesByType = new Map<string, Map<number, string>>();
    await Promise.all(
      Array.from(idsByType.entries()).map(async ([type, idSet]) => {
        const sql = bulkQueryMap[type];
        if (!sql) return;
        try {
          const rows = await rawQuery<{ id: number; name: string }>(sql, [Array.from(idSet), scope.companyId]);
          const map = new Map<number, string>();
          for (const r of rows) map.set(Number(r.id), r.name);
          namesByType.set(type, map);
        } catch (e) { logger.warn(e, "tasks: linked entity table may not exist"); }
      })
    );
    for (const task of tasks) {
      if (task.linkedEntityType && task.linkedEntityId) {
        task.linkedEntityName = namesByType.get(task.linkedEntityType)?.get(Number(task.linkedEntityId)) ?? null;
      }
    }

    res.json(maskFields(req, tasks));
  } catch (err) {
    handleRouteError(err, res, "List tasks error:");
  }
});

router.get("/entity-search", authorize({ feature: "tasks", action: "list" }), async (req, res) => {
  try {
    const scope = req.scope!;
    const { type, q } = req.query as Record<string, string | undefined>;
    if (!type) { res.json({ data: [], total: 0 }); return; }

    const searchMap: Record<string, string> = {
      property_unit: `SELECT id, "unitNumber" AS name FROM property_units WHERE "companyId"=$1 AND "deletedAt" IS NULL AND ("unitNumber" ILIKE $2 OR "buildingName" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      vehicle: `SELECT id, COALESCE("plateNumber", make || ' ' || model) AS name FROM fleet_vehicles WHERE "companyId"=$1 AND "deletedAt" IS NULL AND ("plateNumber" ILIKE $2 OR make ILIKE $2 OR model ILIKE $2) ORDER BY id DESC LIMIT 10`,
      client: `SELECT id, name FROM clients WHERE "companyId"=$1 AND "deletedAt" IS NULL AND (name ILIKE $2 OR phone ILIKE $2) ORDER BY id DESC LIMIT 10`,
      project: `SELECT id, name FROM projects WHERE "companyId"=$1 AND "deletedAt" IS NULL AND name ILIKE $2 ORDER BY id DESC LIMIT 10`,
      contract: `SELECT id, COALESCE("contractNumber", 'عقد #' || id::text) AS name FROM rental_contracts WHERE "companyId"=$1 AND "deletedAt" IS NULL AND ("contractNumber" ILIKE $2 OR "tenantName" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      legal_case: `SELECT id, COALESCE(title, "caseNumber", 'قضية #' || id::text) AS name FROM legal_cases WHERE "companyId"=$1 AND "deletedAt" IS NULL AND (title ILIKE $2 OR "caseNumber" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      maintenance_request: `SELECT id, COALESCE(description, category, 'طلب #' || id) AS name FROM maintenance_requests WHERE "companyId"=$1 AND "deletedAt" IS NULL AND (description ILIKE $2 OR category ILIKE $2) ORDER BY id DESC LIMIT 10`,
    };

    const query = searchMap[type];
    if (!query) { res.json({ data: [], total: 0 }); return; }
    const searchTerm = `%${q || ""}%`;
    const results = await rawQuery<EntitySearchRow>(query, [scope.companyId, searchTerm]);
    res.json(maskFields(req, results));
  } catch (err) {
    handleRouteError(err, res, "Entity search error:");
  }
});

router.get("/:id", authorize({ feature: "tasks", action: "view", resource: { table: "tasks", idParam: "id" } }), async (req, res) => {
  try {
    const scope = req.scope!;
    const id = parseId(req.params.id, "id");
    let scopeCondition = ` AND t."companyId" = $2`;
    const params: unknown[] = [id, scope.companyId];
    if (scope.role === "employee" && !scope.isOwner && scope.activeAssignmentId) {
      // Employee scope: the user can see the task if they're EITHER the
      // primary assignee (tasks.assignedTo) OR a member of the team
      // (task_assignees row). This keeps multi-assignee tasks visible
      // to every team member without giving them broad list permission.
      scopeCondition += ` AND (
        t."assignedTo" = $3
        OR EXISTS (
          SELECT 1 FROM task_assignees ta
          WHERE ta."taskId" = t.id AND ta."assignmentId" = $3 AND ta."removedAt" IS NULL
        )
      )`;
      params.push(scope.activeAssignmentId);
    }
    const rows = await rawQuery<TaskRow & { creatorName?: string | null }>(
      `SELECT t.*, e.name AS "assigneeName",
              creator.name AS "creatorName",
              c.name AS "clientName", c.phone AS "clientPhone"
       FROM tasks t
       LEFT JOIN employee_assignments ea ON ea.id = t."assignedTo"
       LEFT JOIN employees e ON e.id = ea."employeeId" AND e."companyId" = ea."companyId" AND e."deletedAt" IS NULL
       LEFT JOIN employee_assignments cea ON cea.id = t."createdBy"
       LEFT JOIN employees creator ON creator.id = cea."employeeId" AND creator."companyId" = cea."companyId" AND creator."deletedAt" IS NULL
       LEFT JOIN clients c ON c.id = t."clientId" AND c."companyId" = t."companyId" AND c."deletedAt" IS NULL
       WHERE t.id = $1${scopeCondition} AND t."deletedAt" IS NULL`,
      params
    );
    if (rows.length === 0) { throw new NotFoundError("المهمة غير موجودة"); }
    const team = await fetchTaskAssignees(id, scope.companyId);
    res.json(maskFields(req, { ...rows[0], assignees: team }));
  } catch (err) {
    handleRouteError(err, res, "Get task error:");
  }
});

router.post("/", authorize({ feature: "tasks", action: "create" }), async (req, res) => {
  try {
    const scope = req.scope!;
    const { title, description, type, priority, scheduledStart, scheduledEnd, scheduledDate, clientName, clientId, notes, assignedTo: bodyAssignedTo, assignees: bodyAssignees, linkedEntityType, linkedEntityId, autoGenerated } = zodParse(createTaskSchema.safeParse(req.body));

    if (scheduledStart && scheduledEnd && new Date(scheduledEnd) < new Date(scheduledStart)) {
      throw new ValidationError("تاريخ النهاية قبل تاريخ البداية", {
        field: "scheduledEnd",
        fix: "اختر موعد انتهاء بعد موعد البداية",
      });
    }

    let resolvedClientId = clientId || null;
    if (!resolvedClientId && clientName) {
      const clients = await rawQuery<IdRow>(
        `SELECT id FROM clients WHERE name = $1 AND "companyId" = $2 LIMIT 1`,
        [clientName, scope.companyId]
      );
      if (clients.length > 0) resolvedClientId = clients[0].id;
    }
    if (resolvedClientId) {
      const [c] = await rawQuery<{ id: number }>(
        `SELECT id FROM clients WHERE id = $1 AND "companyId" = $2 LIMIT 1`,
        [Number(resolvedClientId), scope.companyId]
      );
      if (!c) {
        throw new ValidationError(`العميل رقم ${resolvedClientId} غير موجود في هذه الشركة`, {
          field: "clientId",
          fix: "اختر عميلاً مسجّلاً أو اتركه فارغاً",
        });
      }
    }


    // ── Resolve the assignee team ──────────────────────────────────────
    // Priority:
    //   1. `assignees` array (multi-member team support).
    //   2. legacy `assignedTo` single field.
    //   3. fallback to the creator (scope.activeAssignmentId).
    // The first element of `assignees` becomes the PRIMARY (mirrored
    // into tasks.assignedTo for back-compat with the old single-column
    // joins that the list view still uses).
    const teamRefs: (string | number)[] = [];
    if (bodyAssignees && bodyAssignees.length > 0) {
      for (const ref of bodyAssignees) teamRefs.push(ref);
    } else if (
      bodyAssignedTo !== undefined &&
      bodyAssignedTo !== null &&
      String(bodyAssignedTo).trim() !== ""
    ) {
      teamRefs.push(bodyAssignedTo);
    }

    let resolvedTeam: number[] = [];
    if (teamRefs.length > 0) {
      // Resolve each reference + dedupe while preserving order.
      const seen = new Set<number>();
      for (const ref of teamRefs) {
        const id = await resolveAssigneeRef(ref, scope.companyId, type || "task");
        if (!seen.has(id)) {
          seen.add(id);
          resolvedTeam.push(id);
        }
      }
    } else if (scope.activeAssignmentId) {
      // Self-assign fallback (existing behavior).
      resolvedTeam = [scope.activeAssignmentId];
    }

    const primaryAssigneeId = resolvedTeam[0] ?? null;

    // Task + its team are written atomically: a failed assignee insert must
    // not leave a task with no team. rawQuery joins the ambient transaction
    // (txStore) automatically, so the existing statements need no rewrite.
    const rows = await withTransaction(async () => {
      const inserted = await rawQuery<TaskRow>(
        `INSERT INTO tasks (
          "companyId", "branchId", "assignmentId", "assignedTo", "createdBy",
          title, description, type, priority, status,
          "scheduledStart", "scheduledEnd", "scheduledDate",
          "clientId", notes, "linkedEntityType", "linkedEntityId", "autoGenerated", "createdAt"
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'pending', $10, $11, $12, $13, $14, $15, $16, $17, NOW())
        RETURNING *`,
        [
          scope.companyId, scope.branchId, scope.activeAssignmentId, primaryAssigneeId, scope.activeAssignmentId,
          title, description || null, type || "task", priority || "medium",
          scheduledStart || null, scheduledEnd || null,
          scheduledDate || (scheduledStart ? scheduledStart.split("T")[0] : null),
          resolvedClientId, notes || null,
          linkedEntityType || null, linkedEntityId || null, autoGenerated || false,
        ]
      );

      if (!inserted[0]) throw new NotFoundError("فشل في إنشاء المهمة");

      // Write the team into task_assignees. The first element is 'primary';
      // subsequent elements are 'member'. ON CONFLICT DO NOTHING absorbs
      // duplicate-row races; any other error rolls back the whole task.
      if (resolvedTeam.length > 0) {
        const taskId = inserted[0].id;
        for (let i = 0; i < resolvedTeam.length; i++) {
          const role = i === 0 ? "primary" : "member";
          await rawQuery(
            `INSERT INTO task_assignees ("companyId", "taskId", "assignmentId", role, "assignedBy")
             VALUES ($1, $2, $3, $4, $5)
             ON CONFLICT DO NOTHING`,
            [scope.companyId, taskId, resolvedTeam[i], role, scope.activeAssignmentId],
          );
        }
      }
      return inserted;
    });

    createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "create", entity: "tasks", entityId: rows[0].id, after: { title, type: type || "task", priority: priority || "medium", assignedTo: primaryAssigneeId, assignees: resolvedTeam, createdBy: scope.activeAssignmentId } }).catch((e) => logger.error(e, "tasks background task failed"));
    emitEvent({ companyId: scope.companyId, branchId: scope.branchId, userId: scope.userId, action: "task.created", entity: "tasks", entityId: rows[0].id, details: JSON.stringify({ title, type: type || "task", priority: priority || "medium", teamSize: resolvedTeam.length }) }).catch((e) => logger.error(e, "tasks background task failed"));

    const team = await fetchTaskAssignees(rows[0].id, scope.companyId);
    res.status(201).json({ ...rows[0], assignees: team });
  } catch (err) { handleRouteError(err, res, "Create task error:"); }
});

router.patch("/:id", authorize({ feature: "tasks", action: "update", resource: { table: "tasks", idParam: "id" } }), async (req, res) => {
  try {
    const scope = req.scope!;
    const id = parseId(req.params.id, "id");
    const { title, description, type, priority, status, scheduledStart, scheduledEnd, scheduledDate, notes, assignedTo: bodyAssignedTo, assignees: bodyAssignees } = zodParse(updateTaskSchema.safeParse(req.body));
    // كمرآة لتحقّق POST: لا يجوز أن تصبح نهاية الجدولة قبل بدايتها بعد التعديل الجزئي.
    if (scheduledStart !== undefined || scheduledEnd !== undefined) {
      const [cur] = await rawQuery<{ scheduledStart: string | null; scheduledEnd: string | null }>(
        `SELECT "scheduledStart", "scheduledEnd" FROM tasks WHERE id = $1 AND "companyId" = $2 AND "deletedAt" IS NULL`,
        [id, scope.companyId],
      );
      const ss = scheduledStart ?? cur?.scheduledStart;
      const se = scheduledEnd ?? cur?.scheduledEnd;
      if (ss && se && new Date(se) < new Date(ss)) {
        throw new ValidationError("تاريخ النهاية قبل تاريخ البداية", { field: "scheduledEnd", fix: "اختر موعد انتهاء بعد موعد البداية" });
      }
    }
    const sets: string[] = [];
    const params: unknown[] = [];
    let idx = 1;

    const addField = (col: string, val: unknown) => {
      if (val !== undefined) { sets.push(`"${col}" = $${idx}`); params.push(val); idx++; }
    };

    addField("title", title);
    addField("description", description);
    addField("type", type);
    addField("priority", priority);
    addField("status", status);
    addField("scheduledStart", scheduledStart);
    addField("scheduledEnd", scheduledEnd);
    addField("scheduledDate", scheduledDate);
    addField("notes", notes);

    // Reassign primary owner if the caller provided assignedTo OR the
    // first element of assignees. The full-team replacement happens
    // after the UPDATE; here we only mirror the primary into the legacy
    // tasks.assignedTo column.
    let primaryReassignTo: number | null | undefined;
    if (bodyAssignees !== undefined) {
      // Resolve team — first element becomes primary. Empty array
      // clears the primary mirror.
      if (bodyAssignees.length === 0) {
        primaryReassignTo = null;
      } else {
        primaryReassignTo = await resolveAssigneeRef(
          bodyAssignees[0],
          scope.companyId,
          type || "task",
        );
      }
    } else if (bodyAssignedTo !== undefined && bodyAssignedTo !== null && String(bodyAssignedTo).trim() !== "") {
      primaryReassignTo = await resolveAssigneeRef(
        bodyAssignedTo,
        scope.companyId,
        type || "task",
      );
    } else if (bodyAssignedTo === null) {
      primaryReassignTo = null;
    }
    if (primaryReassignTo !== undefined) {
      addField("assignedTo", primaryReassignTo);
    }

    if (status === "completed") {
      sets.push(`"completedAt" = NOW()`);
    }

    if (sets.length === 0 && bodyAssignees === undefined) {
      throw new ValidationError("لا توجد بيانات للتحديث");
    }

    let currentStatus: string | undefined;
    if (status) {
      const [current] = await rawQuery<{ status: string }>(
        `SELECT status FROM tasks WHERE id = $1 AND "companyId" = $2 AND "deletedAt" IS NULL`,
        [id, scope.companyId]
      );
      if (!current) throw new NotFoundError("المهمة غير موجودة");
      currentStatus = current.status;
      const allowed = VALID_TASK_TRANSITIONS[currentStatus];
      if (allowed && !allowed.includes(status)) {
        throw new ConflictError(`لا يمكن نقل المهمة من "${currentStatus}" إلى "${status}"`);
      }
    }

    params.push(id);
    let whereClause = `id = $${idx}`;
    idx++;

    params.push(scope.companyId);
    whereClause += ` AND "companyId" = $${idx}`;
    idx++;

    if (currentStatus) {
      params.push(currentStatus);
      whereClause += ` AND status = $${idx}`;
      idx++;
    }

    if (scope.role === "employee" && !scope.isOwner && scope.activeAssignmentId) {
      // Multi-assignee: allow update if user is primary OR a team
      // member. EXISTS subquery is anchored on the task id parameter
      // (already bound at $1 from `params.push(id)` above) so we don't
      // collide with the unqualified UPDATE column references.
      whereClause += ` AND (
        tasks."assignedTo" = $${idx}
        OR EXISTS (
          SELECT 1 FROM task_assignees ta
          WHERE ta."taskId" = tasks.id
            AND ta."companyId" = tasks."companyId"
            AND ta."assignmentId" = $${idx}
            AND ta."removedAt" IS NULL
        )
      )`;
      params.push(scope.activeAssignmentId);
      idx++;
    }

    // If only the team is being modified (no scalar field updates),
    // touch updatedAt so the ownership check still runs through UPDATE.
    if (sets.length === 0) {
      sets.push(`"updatedAt" = NOW()`);
    }
    // Scalar update + team replacement are atomic: a soft-remove of old
    // assignees must not commit without the matching re-role/insert of the
    // new team (or the tasks row update). rawQuery joins the ambient
    // transaction (txStore) automatically.
    const rows = await withTransaction(async () => {
      const updated = await rawQuery<TaskRow>(
        `UPDATE tasks SET ${sets.join(", ")} WHERE ${whereClause} RETURNING *`,
        params,
      );
      if (updated.length === 0) { throw new NotFoundError("المهمة غير موجودة"); }

      // Replace the assignee team if `assignees` was sent. We don't
      // truncate-and-rewrite (audit log integrity); we soft-remove rows
      // no longer in the new list and insert any new ones.
      if (bodyAssignees !== undefined) {
        const resolved: number[] = [];
        const seen = new Set<number>();
        for (const ref of bodyAssignees) {
          const aid = await resolveAssigneeRef(ref, scope.companyId, type || "task");
          if (!seen.has(aid)) {
            seen.add(aid);
            resolved.push(aid);
          }
        }
        const existing = await rawQuery<{ assignmentId: number; role: string }>(
          `SELECT "assignmentId", role FROM task_assignees
           WHERE "taskId" = $1 AND "companyId" = $2 AND "removedAt" IS NULL`,
          [id, scope.companyId],
        );
        const existingSet = new Set(existing.map((r) => r.assignmentId));
        // Remove rows that are no longer in the new team.
        for (const e of existing) {
          if (!resolved.includes(e.assignmentId)) {
            await rawQuery(
              `UPDATE task_assignees SET "removedAt" = NOW()
               WHERE "taskId" = $1 AND "assignmentId" = $2 AND "companyId" = $3 AND "removedAt" IS NULL`,
              [id, e.assignmentId, scope.companyId],
            );
          }
        }
        // Insert / re-role.
        for (let i = 0; i < resolved.length; i++) {
          const role = i === 0 ? "primary" : "member";
          if (existingSet.has(resolved[i])) {
            // Update role on the existing active row.
            await rawQuery(
              `UPDATE task_assignees SET role = $1
               WHERE "taskId" = $2 AND "assignmentId" = $3 AND "companyId" = $4 AND "removedAt" IS NULL`,
              [role, id, resolved[i], scope.companyId],
            );
          } else {
            await rawQuery(
              `INSERT INTO task_assignees ("companyId", "taskId", "assignmentId", role, "assignedBy")
               VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING`,
              [scope.companyId, id, resolved[i], role, scope.activeAssignmentId],
            );
          }
        }
      }
      return updated;
    });

    createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "update", entity: "tasks", entityId: id, after: { title, description, type, priority, status, scheduledStart, scheduledEnd, scheduledDate, notes, assignedTo: primaryReassignTo, assignees: bodyAssignees } }).catch((e) => logger.error(e, "tasks background task failed"));

    if (status) {
      emitEvent({
        companyId: scope.companyId,
        branchId: scope.branchId,
        userId: scope.userId,
        action: `task.${status}`,
        entity: "tasks",
        entityId: id,
        after: {
          status,
          ...(status === "completed" ? { completedAt: rows[0]?.completedAt ?? new Date().toISOString() } : {}),
          assignedTo: rows[0]?.assignedTo ?? null,
          title: rows[0]?.title ?? null,
        },
      }).catch((e) => logger.error(e, "tasks background task failed"));
    } else if (sets.length > 0) {
      emitEvent({
        companyId: scope.companyId,
        branchId: scope.branchId,
        userId: scope.userId,
        action: "task.updated",
        entity: "tasks",
        entityId: id,
        after: { title: rows[0]?.title ?? null },
      }).catch((e) => logger.error(e, "tasks background task failed"));
    }

    const team = await fetchTaskAssignees(id, scope.companyId);
    res.json({ ...rows[0], assignees: team });
  } catch (err) {
    handleRouteError(err, res, "Update task error:");
  }
});

// ── Team management endpoints ─────────────────────────────────────────
// Convenience endpoints for adding/removing a single team member
// without rebuilding the full team via PATCH /:id. Useful for the UI
// "add member" / "remove member" actions.

router.get(
  "/:id/assignees",
  authorize({ feature: "tasks", action: "view", resource: { table: "tasks", idParam: "id" } }),
  async (req, res) => {
    try {
      const scope = req.scope!;
      const id = parseId(req.params.id, "id");
      // Tenant scope check via SELECT.
      const [task] = await rawQuery<{ id: number }>(
        `SELECT id FROM tasks WHERE id = $1 AND "companyId" = $2 AND "deletedAt" IS NULL`,
        [id, scope.companyId],
      );
      if (!task) throw new NotFoundError("المهمة غير موجودة");
      const team = await fetchTaskAssignees(id, scope.companyId);
      res.json(maskFields(req, team));
    } catch (err) {
      handleRouteError(err, res, "List task assignees error:");
    }
  },
);

router.post(
  "/:id/assignees",
  authorize({ feature: "tasks", action: "update", resource: { table: "tasks", idParam: "id" } }),
  async (req, res) => {
    try {
      const scope = req.scope!;
      const id = parseId(req.params.id, "id");
      const { assignmentId, role } = zodParse(assigneeMutationSchema.safeParse(req.body));
      // Verify task exists in this tenant.
      const [task] = await rawQuery<{ id: number }>(
        `SELECT id FROM tasks WHERE id = $1 AND "companyId" = $2 AND "deletedAt" IS NULL`,
        [id, scope.companyId],
      );
      if (!task) throw new NotFoundError("المهمة غير موجودة");
      // Verify the assignment belongs to this company.
      const [assignment] = await rawQuery<{ id: number }>(
        `SELECT id FROM employee_assignments
         WHERE id = $1 AND "companyId" = $2 AND status = 'active'`,
        [assignmentId, scope.companyId],
      );
      if (!assignment) {
        throw new ValidationError(`المسؤول رقم ${assignmentId} غير موجود في هذه الشركة`, {
          field: "assignmentId",
          fix: "اختر موظفاً نشطاً من القائمة",
        });
      }
      // All assignee writes are atomic: a primary-demote + assignedTo mirror
      // must not commit without the matching assignee insert/update. rawQuery
      // joins the ambient transaction (txStore) automatically.
      await withTransaction(async () => {
        // Promotion: if role='primary', demote any existing primary first.
        if (role === "primary") {
          await rawQuery(
            `UPDATE task_assignees SET role = 'member'
             WHERE "taskId" = $1 AND "companyId" = $2 AND role = 'primary' AND "removedAt" IS NULL`,
            [id, scope.companyId],
          );
          // Also mirror into tasks.assignedTo.
          await rawQuery(
            `UPDATE tasks SET "assignedTo" = $1 WHERE id = $2 AND "companyId" = $3`,
            [assignmentId, id, scope.companyId],
          );
        }
        // SELECT-then-INSERT-or-UPDATE in two steps. The audit:schema-
        // drift regex (scripts/src/check-schema-drift.mjs) misreads the
        // upsert clause as a table reference, so we use two queries
        // instead. Two round-trips here are fine — there's no
        // concurrency win to chase, just code aesthetics.
        const [existingRow] = await rawQuery<{ id: number }>(
          `SELECT id FROM task_assignees
           WHERE "taskId" = $1 AND "assignmentId" = $2 AND "companyId" = $3 AND "removedAt" IS NULL
           LIMIT 1`,
          [id, assignmentId, scope.companyId],
        );
        if (existingRow) {
          await rawQuery(
            `UPDATE task_assignees SET role = $1 WHERE id = $2 AND "companyId" = $3`,
            [role, existingRow.id, scope.companyId],
          );
        } else {
          await rawQuery(
            `INSERT INTO task_assignees ("companyId", "taskId", "assignmentId", role, "assignedBy")
             VALUES ($1, $2, $3, $4, $5)`,
            [scope.companyId, id, assignmentId, role, scope.activeAssignmentId],
          );
        }
      });
      createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "assignee.add", entity: "tasks", entityId: id, after: { assignmentId, role } }).catch((e) => logger.error(e, "tasks background task failed"));
      const team = await fetchTaskAssignees(id, scope.companyId);
      res.status(201).json(maskFields(req, team));
    } catch (err) {
      handleRouteError(err, res, "Add task assignee error:");
    }
  },
);

router.delete(
  "/:id/assignees/:assignmentId",
  authorize({ feature: "tasks", action: "update", resource: { table: "tasks", idParam: "id" } }),
  async (req, res) => {
    try {
      const scope = req.scope!;
      const id = parseId(req.params.id, "id");
      const assignmentId = parseId(req.params.assignmentId, "assignmentId");
      // Confirm tenant & task exists.
      const [task] = await rawQuery<{ id: number; assignedTo: number | null }>(
        `SELECT id, "assignedTo" FROM tasks WHERE id = $1 AND "companyId" = $2 AND "deletedAt" IS NULL`,
        [id, scope.companyId],
      );
      if (!task) throw new NotFoundError("المهمة غير موجودة");
      // Remove + primary-promotion are atomic: a removed primary must not
      // commit without the replacement primary (or the assignedTo clear).
      await withTransaction(async () => {
        const [removed] = await rawQuery<{ id: number; role: string }>(
          `UPDATE task_assignees SET "removedAt" = NOW()
           WHERE "taskId" = $1 AND "assignmentId" = $2 AND "companyId" = $3 AND "removedAt" IS NULL
           RETURNING id, role`,
          [id, assignmentId, scope.companyId],
        );
        if (!removed) throw new NotFoundError("هذا المستخدم ليس عضواً في المهمة");
        // If we just removed the primary, promote the oldest remaining
        // member to primary (and mirror to tasks.assignedTo). If the team
        // is now empty, clear assignedTo too.
        if (removed.role === "primary") {
          const [next] = await rawQuery<{ id: number; assignmentId: number }>(
            `SELECT id, "assignmentId" FROM task_assignees
             WHERE "taskId" = $1 AND "companyId" = $2 AND "removedAt" IS NULL
             ORDER BY "assignedAt" ASC LIMIT 1`,
            [id, scope.companyId],
          );
          if (next) {
            await rawQuery(
              `UPDATE task_assignees SET role = 'primary' WHERE id = $1 AND "companyId" = $2`,
              [next.id, scope.companyId],
            );
            await rawQuery(
              `UPDATE tasks SET "assignedTo" = $1 WHERE id = $2 AND "companyId" = $3`,
              [next.assignmentId, id, scope.companyId],
            );
          } else {
            await rawQuery(
              `UPDATE tasks SET "assignedTo" = NULL WHERE id = $1 AND "companyId" = $2`,
              [id, scope.companyId],
            );
          }
        }
      });
      createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "assignee.remove", entity: "tasks", entityId: id, after: { assignmentId } }).catch((e) => logger.error(e, "tasks background task failed"));
      const team = await fetchTaskAssignees(id, scope.companyId);
      res.json(maskFields(req, team));
    } catch (err) {
      handleRouteError(err, res, "Remove task assignee error:");
    }
  },
);

router.delete("/:id", authorize({ feature: "tasks", action: "delete", resource: { table: "tasks", idParam: "id" } }), async (req, res) => {
  try {
    const scope = req.scope!;
    const id = parseId(req.params.id, "id");
    const beforeParams: any[] = [id, scope.companyId];
    let beforeWhere = `id = $1 AND "companyId" = $2`;
    if (scope.role === "employee" && !scope.isOwner && scope.activeAssignmentId) {
      beforeWhere += ` AND "assignedTo" = $3`;
      beforeParams.push(scope.activeAssignmentId);
    }
    const [before] = await rawQuery<TaskRow>(`SELECT * FROM tasks WHERE ${beforeWhere}`, beforeParams);
    if (!before) { throw new NotFoundError("المهمة غير موجودة"); }

    // NF-TASK-01 — completed / cancelled tasks are the historical record
    // for retrospectives, KPIs and SLA reports. Allowing them to be
    // soft-deleted erases that history; restrict delete to tasks that
    // haven't yet recorded an outcome.
    if (before.status && !["pending", "in_progress", "blocked"].includes(String(before.status))) {
      throw new ConflictError(
        `لا يمكن حذف مهمة بحالة "${before.status}"`,
        { field: "status", fix: "أرشِف المهمة بدلاً من الحذف" }
      );
    }

    const params: unknown[] = [id, scope.companyId];
    let whereClause = `id = $1 AND "companyId" = $2`;

    if (scope.role === "employee" && !scope.isOwner && scope.activeAssignmentId) {
      whereClause += ` AND "assignedTo" = $3`;
      params.push(scope.activeAssignmentId);
    }

    const rows = await rawQuery<IdRow>(
      `UPDATE tasks SET "deletedAt" = NOW() WHERE ${whereClause} AND "deletedAt" IS NULL RETURNING id`,
      params
    );
    if (rows.length === 0) { throw new NotFoundError("المهمة غير موجودة"); }
    createAuditLog({ companyId: scope.companyId, userId: scope.userId, action: "delete", entity: "tasks", entityId: id, before }).catch((e) => logger.error(e, "tasks background task failed"));
    emitEvent({ companyId: scope.companyId, branchId: scope.branchId, userId: scope.userId, action: "task.deleted", entity: "tasks", entityId: id, details: JSON.stringify({ title: before?.title }) }).catch((e) => logger.error(e, "tasks background task failed"));
    res.json({ success: true });
  } catch (err) {
    handleRouteError(err, res, "Delete task error:");
  }
});

export default router;
