import { handleRouteError } from "../lib/errorHandler.js";
import { Router } from "express";
import { rawQuery } from "../lib/rawdb.js";
import { authMiddleware } from "../middlewares/authMiddleware.js";
import { buildScopedWhere, parseScopeFilters } from "../lib/scopedQuery.js";
import { loadBalanceAssign } from "../lib/algorithms.js";

const router = Router();
router.use(authMiddleware);

router.get("/", async (req, res) => {
  try {
    const scope = req.scope!;
    const { status = "", date = "" } = req.query as any;

    const filters = parseScopeFilters(req);
    const { where: baseWhere, params, nextParamIndex } = buildScopedWhere(scope, filters, {
      companyColumn: 't."companyId"',
      branchColumn: 't."branchId"',
      enforceBranchScope: true,
    });
    let where = baseWhere;
    let paramIdx = nextParamIndex;

    if (status) {
      where += ` AND t.status = $${paramIdx}`;
      params.push(status);
      paramIdx++;
    }

    if (date) {
      where += ` AND t."scheduledDate" = $${paramIdx}`;
      params.push(date);
      paramIdx++;
    }

    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      where += ` AND t."assignedTo" = $${paramIdx}`;
      params.push(scope.activeAssignmentId);
      paramIdx++;
    }

    const { linkedEntityType, linkedEntityId, includeRelatedMaintenance, relatedUnitId } = req.query as any;
    if (linkedEntityType && linkedEntityId && includeRelatedMaintenance === "true" && linkedEntityType === "property_unit") {
      where += ` AND ((t."linkedEntityType" = $${paramIdx} AND t."linkedEntityId" = $${paramIdx + 1}) OR (t."linkedEntityType" = 'maintenance_request' AND t."linkedEntityId" IN (SELECT id FROM maintenance_requests WHERE "unitId" = $${paramIdx + 1} AND "companyId" = $${paramIdx + 2})))`;
      params.push(linkedEntityType, Number(linkedEntityId), scope.companyId);
      paramIdx += 3;
    } else {
      if (linkedEntityType) {
        where += ` AND t."linkedEntityType" = $${paramIdx}`;
        params.push(linkedEntityType);
        paramIdx++;
      }
      if (linkedEntityId) {
        where += ` AND t."linkedEntityId" = $${paramIdx}`;
        params.push(Number(linkedEntityId));
        paramIdx++;
      }
    }
    if (relatedUnitId && linkedEntityType === "maintenance_request") {
      where += ` AND t."linkedEntityId" IN (SELECT mr2.id FROM maintenance_requests mr2 WHERE mr2."unitId" = $${paramIdx})`;
      params.push(Number(relatedUnitId));
      paramIdx++;
    }

    const tasks = await rawQuery<any>(
      `SELECT t.id, t.title, t.description, t.status, t.priority, t.type,
              t."scheduledDate", t."scheduledStart", t."scheduledEnd",
              t."completedAt", t."createdAt", t.notes,
              t."clientId",
              t."linkedEntityType", t."linkedEntityId", t."autoGenerated",
              e.name AS "assigneeName",
              c.name AS "clientName", c.phone AS "clientPhone"
       FROM tasks t
       LEFT JOIN employee_assignments ea ON ea.id = t."assignedTo"
       LEFT JOIN employees e ON e.id = ea."employeeId"
       LEFT JOIN clients c ON c.id = t."clientId"
       WHERE ${where}
       ORDER BY t.priority DESC, t."scheduledDate" ASC NULLS LAST`,
      params
    );

    // Resolve linkedEntityName in bulk: group ids by type, then issue
    // one tenant-scoped query per distinct type (small constant set).
    const idsByType = new Map<string, Set<number>>();
    for (const task of tasks) {
      if (task.linkedEntityType && task.linkedEntityId) {
        if (!idsByType.has(task.linkedEntityType)) idsByType.set(task.linkedEntityType, new Set());
        idsByType.get(task.linkedEntityType)!.add(Number(task.linkedEntityId));
      }
    }
    const bulkQueryMap: Record<string, string> = {
      property_unit: `SELECT id, "unitNumber" AS name FROM property_units WHERE id = ANY($1) AND "companyId"=$2`,
      vehicle: `SELECT id, COALESCE("plateNumber", make || ' ' || model) AS name FROM vehicles WHERE id = ANY($1) AND "companyId"=$2`,
      client: `SELECT id, name FROM clients WHERE id = ANY($1) AND "companyId"=$2`,
      project: `SELECT id, name FROM projects WHERE id = ANY($1) AND "companyId"=$2`,
      contract: `SELECT id, COALESCE(ref, 'عقد #' || id) AS name FROM contracts WHERE id = ANY($1) AND "companyId"=$2`,
      legal_case: `SELECT id, COALESCE(title, "caseNumber", 'قضية #' || id) AS name FROM legal_cases WHERE id = ANY($1) AND "companyId"=$2`,
      maintenance_request: `SELECT id, COALESCE(description, category, 'طلب #' || id) AS name FROM maintenance_requests WHERE id = ANY($1) AND "companyId"=$2`,
    };
    const namesByType = new Map<string, Map<number, string>>();
    await Promise.all(
      Array.from(idsByType.entries()).map(async ([type, idSet]) => {
        const sql = bulkQueryMap[type];
        if (!sql) return;
        try {
          const rows = await rawQuery<{ id: number; name: string }>(sql, [Array.from(idSet), scope.companyId]);
          const map = new Map<number, string>();
          for (const r of rows) map.set(Number(r.id), r.name);
          namesByType.set(type, map);
        } catch { /* table may not exist in some deployments */ }
      })
    );
    for (const task of tasks) {
      if (task.linkedEntityType && task.linkedEntityId) {
        task.linkedEntityName = namesByType.get(task.linkedEntityType)?.get(Number(task.linkedEntityId)) ?? null;
      }
    }

    res.json(tasks);
  } catch (err) {
    handleRouteError(err, res, "List tasks error:");
  }
});

router.get("/entity-search", async (req, res) => {
  try {
    const scope = req.scope!;
    const { type, q } = req.query as any;
    if (!type) { res.json([]); return; }

    const searchMap: Record<string, string> = {
      property_unit: `SELECT id, "unitNumber" AS name FROM property_units WHERE "companyId"=$1 AND ("unitNumber" ILIKE $2 OR "buildingName" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      vehicle: `SELECT id, COALESCE("plateNumber", make || ' ' || model) AS name FROM vehicles WHERE "companyId"=$1 AND ("plateNumber" ILIKE $2 OR make ILIKE $2 OR model ILIKE $2) ORDER BY id DESC LIMIT 10`,
      client: `SELECT id, name FROM clients WHERE "companyId"=$1 AND (name ILIKE $2 OR phone ILIKE $2) ORDER BY id DESC LIMIT 10`,
      project: `SELECT id, name FROM projects WHERE "companyId"=$1 AND name ILIKE $2 ORDER BY id DESC LIMIT 10`,
      contract: `SELECT id, COALESCE(ref, 'عقد #' || id) AS name FROM contracts WHERE "companyId"=$1 AND (ref ILIKE $2 OR "tenantName" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      legal_case: `SELECT id, COALESCE(title, "caseNumber", 'قضية #' || id) AS name FROM legal_cases WHERE "companyId"=$1 AND (title ILIKE $2 OR "caseNumber" ILIKE $2) ORDER BY id DESC LIMIT 10`,
      maintenance_request: `SELECT id, COALESCE(description, category, 'طلب #' || id) AS name FROM maintenance_requests WHERE "companyId"=$1 AND (description ILIKE $2 OR category ILIKE $2) ORDER BY id DESC LIMIT 10`,
    };

    const query = searchMap[type];
    if (!query) { res.json([]); return; }
    const searchTerm = `%${q || ""}%`;
    const results = await rawQuery<any>(query, [scope.companyId, searchTerm]);
    res.json(results);
  } catch (err) {
    handleRouteError(err, res, "Entity search error:");
  }
});

router.get("/:id", async (req, res) => {
  try {
    const scope = req.scope!;
    let scopeCondition = ` AND t."companyId" = $2`;
    const params: any[] = [req.params.id, scope.companyId];
    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      scopeCondition += ` AND t."assignedTo" = $3`;
      params.push(scope.activeAssignmentId);
    }
    const rows = await rawQuery<any>(
      `SELECT t.*, e.name AS "assigneeName",
              c.name AS "clientName", c.phone AS "clientPhone"
       FROM tasks t
       LEFT JOIN employee_assignments ea ON ea.id = t."assignedTo"
       LEFT JOIN employees e ON e.id = ea."employeeId"
       LEFT JOIN clients c ON c.id = t."clientId"
       WHERE t.id = $1${scopeCondition}`,
      params
    );
    if (rows.length === 0) { res.status(404).json({ error: "المهمة غير موجودة" }); return; }
    res.json(rows[0]);
  } catch (err) {
    handleRouteError(err, res, "Get task error:");
  }
});

router.post("/", async (req, res) => {
  try {
    const scope = req.scope!;
    const { title, description, type, priority, scheduledStart, scheduledEnd, scheduledDate, clientName, clientId, notes, assignedTo: bodyAssignedTo, linkedEntityType, linkedEntityId, autoGenerated } = req.body;

    if (!title) { res.status(400).json({ error: "العنوان مطلوب" }); return; }

    let resolvedClientId = clientId || null;
    if (!resolvedClientId && clientName) {
      const clients = await rawQuery<any>(
        `SELECT id FROM clients WHERE name = $1 AND "companyId" = $2 LIMIT 1`,
        [clientName, scope.companyId]
      );
      if (clients.length > 0) resolvedClientId = clients[0].id;
    }


      let finalAssignedTo = scope.activeAssignmentId;
      if (bodyAssignedTo === "auto") {
        const smartResult = await loadBalanceAssign(scope.companyId, type || "task");
        if (smartResult) finalAssignedTo = smartResult.assignmentId;
      } else if (bodyAssignedTo) {
        finalAssignedTo = bodyAssignedTo;
      }
  
    const rows = await rawQuery<any>(
      `INSERT INTO tasks (
        "companyId", "branchId", "assignmentId", "assignedTo",
        title, description, type, priority, status,
        "scheduledStart", "scheduledEnd", "scheduledDate",
        "clientId", notes, "linkedEntityType", "linkedEntityId", "autoGenerated", "createdAt"
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending', $9, $10, $11, $12, $13, $14, $15, $16, NOW())
      RETURNING *`,
      [
        scope.companyId, scope.branchId, scope.activeAssignmentId, finalAssignedTo,
        title, description || null, type || "task", priority || "medium",
        scheduledStart || null, scheduledEnd || null,
        scheduledDate || (scheduledStart ? scheduledStart.split("T")[0] : null),
        resolvedClientId, notes || null,
        linkedEntityType || null, linkedEntityId || null, autoGenerated || false,
      ]
    );

    res.status(201).json(rows[0]);
  } catch (err) {
    console.error("Create task error:", err);
    res.status(500).json({ error: "خطأ في إنشاء المهمة" });
  }
});

router.patch("/:id", async (req, res) => {
  try {
    const scope = req.scope!;
    const { title, description, type, priority, status, scheduledStart, scheduledEnd, scheduledDate, notes } = req.body;
    const sets: string[] = [];
    const params: any[] = [];
    let idx = 1;

    const addField = (col: string, val: any) => {
      if (val !== undefined) { sets.push(`"${col}" = $${idx}`); params.push(val); idx++; }
    };

    addField("title", title);
    addField("description", description);
    addField("type", type);
    addField("priority", priority);
    addField("status", status);
    addField("scheduledStart", scheduledStart);
    addField("scheduledEnd", scheduledEnd);
    addField("scheduledDate", scheduledDate);
    addField("notes", notes);

    if (status === "completed") {
      sets.push(`"completedAt" = NOW()`);
    }

    if (sets.length === 0) { res.status(400).json({ error: "لا توجد بيانات للتحديث" }); return; }

    params.push(req.params.id);
    let whereClause = `id = $${idx}`;
    idx++;

    params.push(scope.companyId);
    whereClause += ` AND "companyId" = $${idx}`;
    idx++;

    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      whereClause += ` AND "assignedTo" = $${idx}`;
      params.push(scope.activeAssignmentId);
      idx++;
    }

    const rows = await rawQuery<any>(
      `UPDATE tasks SET ${sets.join(", ")} WHERE ${whereClause} RETURNING *`,
      params
    );

    if (rows.length === 0) { res.status(404).json({ error: "المهمة غير موجودة" }); return; }
    res.json(rows[0]);
  } catch (err) {
    console.error("Update task error:", err);
    res.status(500).json({ error: "خطأ في تحديث المهمة" });
  }
});

router.delete("/:id", async (req, res) => {
  try {
    const scope = req.scope!;
    const params: any[] = [req.params.id, scope.companyId];
    let whereClause = `id = $1 AND "companyId" = $2`;

    if (!scope.isOwner && scope.role !== "owner" && scope.role !== "general_manager" && scope.role === "employee" && scope.activeAssignmentId) {
      whereClause += ` AND "assignedTo" = $3`;
      params.push(scope.activeAssignmentId);
    }

    const rows = await rawQuery<any>(
      `DELETE FROM tasks WHERE ${whereClause} RETURNING id`,
      params
    );
    if (rows.length === 0) { res.status(404).json({ error: "المهمة غير موجودة" }); return; }
    res.json({ success: true });
  } catch (err) {
    console.error("Delete task error:", err);
    res.status(500).json({ error: "خطأ في حذف المهمة" });
  }
});

export default router;
