/**
 * Thin HTTP wrapper around the ZATCA Fatoora API.
 *
 * Uses Node 20+'s built-in `fetch` so no axios / node-fetch dep is
 * needed. The functions here are intentionally **leaf** wrappers:
 * they build a request, send it, parse the response, and return a
 * `ClearanceResult` (or throw with a clear shape on transport errors).
 * Higher-level orchestration (PIH chaining, ICV reservation, retry
 * queue) lives in the route handler.
 *
 * Production guard: the timeout default and retry-disable settings
 * match the Fatoora SLO so a network hiccup doesn't double-submit an
 * invoice. Callers that need different behaviour pass an explicit
 * `signal` for cancellation.
 */
import {
  buildFatoraUrl,
  CLEARANCE_SINGLE_PATH,
  REPORTING_SINGLE_PATH,
  COMPLIANCE_CSID_PATH,
  COMPLIANCE_INVOICE_CHECK_PATH,
  PRODUCTION_CSID_PATH,
} from "./endpoints.js";
import { basicAuthHeader, commonFatoraHeaders, type ZatcaCredentials } from "./auth.js";
import { parseClearanceResponse } from "./response.js";
import type { ClearanceResult, ZatcaEnvironment } from "./types.js";

const DEFAULT_TIMEOUT_MS = Number(process.env.ZATCA_CLEARANCE_TIMEOUT_MS ?? 30_000);

export interface InvoiceSubmission {
  /** UUID generated by the seller for this invoice (also embedded in the XML). */
  invoiceUuid: string;
  /** Base64 SHA-256 hash of the canonicalized invoice XML (= QR tag 6). */
  invoiceHashBase64: string;
  /** Full UBL XML with the <ext:UBLExtensions> signature populated. */
  signedXmlBase64: string;
}

/**
 * Clear a Standard (B2B) invoice. Synchronous from the seller's
 * perspective — the response body either contains the cleared XML
 * (with the QR + ZATCA signature embedded) or a rejection.
 */
export async function clearStandardInvoice(opts: {
  env: ZatcaEnvironment;
  creds: ZatcaCredentials;
  submission: InvoiceSubmission;
  signal?: AbortSignal;
}): Promise<ClearanceResult> {
  const url = buildFatoraUrl(opts.env, CLEARANCE_SINGLE_PATH);
  const body = JSON.stringify({
    invoiceHash: opts.submission.invoiceHashBase64,
    uuid: opts.submission.invoiceUuid,
    invoice: opts.submission.signedXmlBase64,
  });
  const headers = {
    ...commonFatoraHeaders(),
    Authorization: basicAuthHeader(opts.creds),
    // The Clearance-Status header tells ZATCA whether to attempt
    // clearance (1) or treat the call as a re-submission (0). For
    // first-attempt invoices we always set 1; the retry worker passes
    // 0 explicitly when re-sending after a transient error.
    "Clearance-Status": "1",
  };
  const json = await postJson(url, body, headers, opts.signal);
  return parseClearanceResponse(json, opts.submission.invoiceUuid);
}

/**
 * Report a Simplified (B2C) invoice. The seller delivers the invoice
 * to the buyer immediately; ZATCA just records it.
 */
export async function reportSimplifiedInvoice(opts: {
  env: ZatcaEnvironment;
  creds: ZatcaCredentials;
  submission: InvoiceSubmission;
  signal?: AbortSignal;
}): Promise<ClearanceResult> {
  const url = buildFatoraUrl(opts.env, REPORTING_SINGLE_PATH);
  const body = JSON.stringify({
    invoiceHash: opts.submission.invoiceHashBase64,
    uuid: opts.submission.invoiceUuid,
    invoice: opts.submission.signedXmlBase64,
  });
  const headers = {
    ...commonFatoraHeaders(),
    Authorization: basicAuthHeader(opts.creds),
  };
  const json = await postJson(url, body, headers, opts.signal);
  return parseClearanceResponse(json, opts.submission.invoiceUuid);
}

/**
 * Onboarding: request a compliance CSID using a CSR + the OTP the
 * seller generated from the ZATCA portal. Anonymous endpoint — no
 * Basic auth header.
 */
export async function requestComplianceCsid(opts: {
  env: ZatcaEnvironment;
  csrBase64: string;
  otp: string;
  signal?: AbortSignal;
}): Promise<{ binarySecurityToken: string; secret: string; requestId: string }> {
  const url = buildFatoraUrl(opts.env, COMPLIANCE_CSID_PATH);
  const headers = {
    ...commonFatoraHeaders(),
    OTP: opts.otp,
  };
  const body = JSON.stringify({ csr: opts.csrBase64 });
  const json = await postJson(url, body, headers, opts.signal);
  return {
    binarySecurityToken: String(json?.binarySecurityToken ?? ""),
    secret: String(json?.secret ?? ""),
    requestId: String(json?.requestID ?? json?.requestId ?? ""),
  };
}

/**
 * Onboarding: run a single test-pack invoice through the compliance
 * checker. The 6-invoice test pack is just six calls to this function;
 * the runner aggregates the results.
 */
export async function complianceInvoiceCheck(opts: {
  env: ZatcaEnvironment;
  creds: ZatcaCredentials;
  submission: InvoiceSubmission;
  signal?: AbortSignal;
}): Promise<ClearanceResult> {
  const url = buildFatoraUrl(opts.env, COMPLIANCE_INVOICE_CHECK_PATH);
  const body = JSON.stringify({
    invoiceHash: opts.submission.invoiceHashBase64,
    uuid: opts.submission.invoiceUuid,
    invoice: opts.submission.signedXmlBase64,
  });
  const headers = {
    ...commonFatoraHeaders(),
    Authorization: basicAuthHeader(opts.creds),
  };
  const json = await postJson(url, body, headers, opts.signal);
  return parseClearanceResponse(json, opts.submission.invoiceUuid);
}

/**
 * Onboarding: promote a compliance CSID to production after the test
 * pack passes. ZATCA returns a fresh binarySecurityToken + secret
 * scoped to production.
 */
export async function requestProductionCsid(opts: {
  env: ZatcaEnvironment;
  /** The compliance CSID's credentials — used to authenticate THIS call. */
  complianceCreds: ZatcaCredentials;
  /** ZATCA's request ID from the original compliance issuance. */
  complianceRequestId: string;
  signal?: AbortSignal;
}): Promise<{ binarySecurityToken: string; secret: string }> {
  const url = buildFatoraUrl(opts.env, PRODUCTION_CSID_PATH);
  const body = JSON.stringify({ compliance_request_id: opts.complianceRequestId });
  const headers = {
    ...commonFatoraHeaders(),
    Authorization: basicAuthHeader(opts.complianceCreds),
  };
  const json = await postJson(url, body, headers, opts.signal);
  return {
    binarySecurityToken: String(json?.binarySecurityToken ?? ""),
    secret: String(json?.secret ?? ""),
  };
}

// ─────────────────────────────────────────────────────────────────────
// Internal: POST helper with timeout + structured transport errors
// ─────────────────────────────────────────────────────────────────────

async function postJson(
  url: string,
  body: string,
  headers: Record<string, string>,
  externalSignal?: AbortSignal,
): Promise<Record<string, unknown>> {
  const controller = new AbortController();
  const timeoutId = setTimeout(
    () => controller.abort(new Error(`ZATCA request timed out after ${DEFAULT_TIMEOUT_MS}ms`)),
    DEFAULT_TIMEOUT_MS,
  );
  // Plumb the external signal through too so callers can cancel.
  externalSignal?.addEventListener("abort", () => controller.abort(externalSignal.reason));

  try {
    const response = await fetch(url, {
      method: "POST",
      body,
      headers,
      signal: controller.signal,
    });

    const text = await response.text();
    let parsed: unknown;
    try {
      parsed = text ? JSON.parse(text) : {};
    } catch {
      throw new ZatcaTransportError(
        `ZATCA returned non-JSON response (${response.status})`,
        response.status,
        text.slice(0, 2000),
      );
    }

    if (!response.ok) {
      // Surface the body for audit / debugging. ZATCA usually returns
      // structured validationResults even on 4xx, so we let the parser
      // see them too via the throw payload.
      throw new ZatcaTransportError(
        `ZATCA returned HTTP ${response.status}`,
        response.status,
        parsed,
      );
    }

    return parsed as Record<string, unknown>;
  } finally {
    clearTimeout(timeoutId);
  }
}

/**
 * Transport-level error from a ZATCA call. Caller decides whether to
 * retry (5xx) or surface to the user (4xx). The `body` field carries
 * the parsed (or truncated) response so the audit log captures what
 * ZATCA actually said.
 */
export class ZatcaTransportError extends Error {
  constructor(
    message: string,
    public readonly httpStatus: number,
    public readonly body: unknown,
  ) {
    super(message);
    this.name = "ZatcaTransportError";
  }
}
