#!/bin/bash
#
# dump-seed.sh — extract the minimal reference rows needed for a fresh
# local DB to be functional for development + verification testing.
#
# What gets dumped:
#   • companies              — at least 1 company so scope works
#   • branches               — at least 1 branch per company
#   • job_titles             — referenced by employee_assignments
#   • permissions            — the catalog
#   • roles + role_permissions  — RBAC seed
#   • chart_of_accounts      — needed for any GL posting test
#   • currencies             — referenced by invoices
#   • system_settings        — currency / timezone defaults
#   • module_dashboards (catalog) — needed by /module-dashboards routes
#
# What is DELIBERATELY NOT dumped:
#   ✗ users          — created by db/seed-admin-user.sql with a known
#                      test password instead of leaking real hashes
#   ✗ employees      — same; created by seed-admin-user.sql
#   ✗ employee_assignments — same
#   ✗ refresh_tokens — never
#   ✗ audit_logs / event_logs — empty on fresh
#   ✗ invoices / journal_entries / fleet_* / property_* / etc. —
#                      transactional data, must stay clean
#
# Run on Replit (where DATABASE_URL points at the live DB):
#   DATABASE_URL=postgres://... bash db/dump-seed.sh
#
# Or via:
#   pnpm db:dump-seed

set -e

if [ -z "$DATABASE_URL" ]; then
  echo "ERROR: DATABASE_URL must be set." >&2
  exit 1
fi

OUT="db/seed.sql"
TMP="$(mktemp)"

# Reference tables only — read the comment block at the top of this file
# for what gets dumped vs not. Any ADDITIONS here must be safe to ship in
# git (no PII, no real customer data, no production secrets).
REFERENCE_TABLES=(
  companies
  branches
  job_titles
  permissions
  roles
  role_permissions
  chart_of_accounts
  currencies
  system_settings
  module_dashboards
)

# Build the -t flags for pg_dump
DUMP_FLAGS=""
for t in "${REFERENCE_TABLES[@]}"; do
  DUMP_FLAGS="$DUMP_FLAGS -t $t"
done

echo "→ Dumping reference rows from \$DATABASE_URL into $OUT"
echo "  Tables: ${REFERENCE_TABLES[*]}"

pg_dump \
  --data-only \
  --no-owner \
  --no-acl \
  --no-comments \
  --column-inserts \
  $DUMP_FLAGS \
  "$DATABASE_URL" > "$TMP" 2> /tmp/dump-seed.err || {
    echo "WARN: some tables missing on the live DB. Stderr:" >&2
    cat /tmp/dump-seed.err >&2
    echo "Continuing with whatever did dump..."
  }

# Prepend a header + an explicit "TRUNCATE then INSERT" wrapper so the
# seed is idempotent: re-running it on a populated dev DB resets the
# reference rows without touching transactional data.
{
  echo "-- db/seed.sql — minimal reference rows for fresh local Postgres"
  echo "-- AUTO-GENERATED by db/dump-seed.sh — do not hand-edit."
  echo "--"
  echo "-- Apply with: psql \"$DATABASE_URL\" -f db/seed.sql"
  echo "-- Or via:    pnpm db:bootstrap"
  echo
  cat "$TMP"
} > "$OUT"

rm -f "$TMP" /tmp/dump-seed.err

LINE_COUNT=$(wc -l < "$OUT")
INSERT_COUNT=$(grep -c '^INSERT INTO' "$OUT" || echo 0)

echo "✓ Wrote $OUT"
echo "  Lines:   $LINE_COUNT"
echo "  INSERTs: $INSERT_COUNT"
echo
echo "Next step: review the diff (REDACT any PII you spot), commit,"
echo "and push to the Phase 2 branch. The companion seed-admin-user.sql"
echo "creates a test admin separately — never dump real users into seed.sql."
