-- db/seed.sql — minimal reference rows for fresh local Postgres
-- AUTO-GENERATED by db/dump-seed.sh — do not hand-edit.
--
-- Apply with: psql "postgresql://postgres:password@helium/heliumdb?sslmode=disable" -f db/seed.sql
-- Or via:    pnpm db:bootstrap

--
-- PostgreSQL database dump
--

\restrict 2TH4EZfPNHHlpzq6joygm408RgsP6390ntZGiNHFiYbq6mGYKtGZkjAZ7VqRfy9

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: companies; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.companies (id, name, "nameEn", "crNumber", "vatNumber", domain, "pbxPrefix", "logoUrl", address, phone, email, status, "createdAt") VALUES (1, 'مجموعة الدور', 'Al Door Group', '1010000001', '300000000000003', NULL, NULL, NULL, 'الرياض، المملكة العربية السعودية', '0112000001', 'info@door.sa', 'active', '2026-04-11 18:16:01.492201');


--
-- Data for Name: branches; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.branches (id, "companyId", name, address, lat, lon, phone, status, "createdAt", "logoUrl", "taxNumber", "crNumber", email, website, "footerText", "nameEn", city) VALUES (1, 1, 'الفرع الرئيسي — الرياض', 'طريق الملك فهد، الرياض', NULL, NULL, '0112000002', 'active', '2026-04-11 18:16:01.492201', NULL, NULL, NULL, 'main@door.sa', NULL, NULL, 'Main Branch — Riyadh', 'الرياض');
INSERT INTO public.branches (id, "companyId", name, address, lat, lon, phone, status, "createdAt", "logoUrl", "taxNumber", "crNumber", email, website, "footerText", "nameEn", city) VALUES (2, 1, 'فرع مكة', NULL, NULL, NULL, NULL, 'active', '2026-04-13 23:13:20.089328', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);


--
-- Data for Name: chart_of_accounts; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (123, 1, '1100', 'النقد والبنوك', 'asset', '1000', 'active', '2026-04-11 18:17:22.869479', NULL, NULL, 1, true, true, 0.00, -16388.50, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:22.869479+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (126, 1, '1200', 'الذمم المدينة', 'asset', '1000', 'active', '2026-04-11 18:17:23.339388', NULL, NULL, 1, true, true, 0.00, 317123.85, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.339388+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (124, 1, '1101', 'الصندوق', 'asset', '1100', 'active', '2026-04-11 18:17:23.022876', NULL, NULL, 1, true, true, 0.00, 503500.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.022876+00', NULL, 'cash', 'cash', 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (134, 1, '3100', 'رأس المال', 'equity', '3000', 'active', '2026-04-11 18:17:24.57777', NULL, NULL, 1, true, true, 0.00, 500000.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:24.57777+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (138, 1, '4200', 'إيرادات الخدمات', 'revenue', '4000', 'active', '2026-04-11 18:17:25.20886', NULL, NULL, 1, true, true, 0.00, 100000.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.20886+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (122, 1, '1000', 'الأصول', 'asset', NULL, 'active', '2026-04-11 18:17:22.701678', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:22.701678+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (127, 1, '1300', 'المخزون', 'asset', '1000', 'active', '2026-04-11 18:17:23.493382', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.493382+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (140, 1, '5100', 'الرواتب والأجور', 'expense', '5000', 'active', '2026-04-11 18:17:25.529069', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.529069+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (141, 1, '5200', 'الإيجارات', 'expense', '5000', 'active', '2026-04-11 18:17:25.685645', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.685645+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (142, 1, '5300', 'المرافق', 'expense', '5000', 'active', '2026-04-11 18:17:25.838371', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.838371+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (143, 1, '5400', 'مصاريف عامة', 'expense', '5000', 'active', '2026-04-11 18:17:25.990662', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.990662+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (129, 1, '2000', 'الخصوم', 'liability', NULL, 'active', '2026-04-11 18:17:23.806522', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.806522+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (133, 1, '3000', 'حقوق الملكية', 'equity', NULL, 'active', '2026-04-11 18:17:24.42537', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:24.42537+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (135, 1, '3200', 'الأرباح المحتجزة', 'equity', '3000', 'active', '2026-04-11 18:17:24.733876', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:24.733876+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (137, 1, '4100', 'إيرادات المبيعات', 'revenue', '4000', 'active', '2026-04-11 18:17:25.054242', NULL, NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.054242+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (136, 1, '4000', 'الإيرادات', 'revenue', NULL, 'active', '2026-04-11 18:17:24.884092', NULL, NULL, 1, true, true, 0.00, 1491.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:24.884092+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (144, 1, '9999', 'فروقات التقريب', 'expense', NULL, 'active', '2026-04-11 18:17:26.145883', 'Rounding Differences', NULL, 1, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:26.145883+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (132, 1, '2300', 'الرواتب المستحقة', 'liability', '2000', 'active', '2026-04-11 18:17:24.272135', NULL, NULL, 1, true, true, 0.00, 223.65, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:24.272135+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (131, 1, '2200', 'ضريبة القيمة المضافة', 'liability', '2000', 'active', '2026-04-11 18:17:24.117202', NULL, NULL, 1, true, true, 0.00, 11250.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:24.117202+00', NULL, NULL, NULL, 'credit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (139, 1, '5000', 'المصروفات', 'expense', NULL, 'active', '2026-04-11 18:17:25.361937', NULL, NULL, 1, true, true, 0.00, 2400.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:25.361937+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (128, 1, '1400', 'الأصول الثابتة', 'asset', '1000', 'active', '2026-04-11 18:17:23.651747', NULL, NULL, 1, true, true, 0.00, 55000.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.651747+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (125, 1, '1102', 'البنك الأهلي', 'asset', '1100', 'active', '2026-04-11 18:17:23.185603', NULL, NULL, 1, true, true, 0.00, -201250.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.185603+00', NULL, 'bank', 'bank', 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (145, 1, '1350', 'أعمال تحت التنفيذ (WIP)', 'asset', NULL, 'active', '2026-04-13 17:07:35.079902', 'Work In Progress', NULL, 3, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-13 17:07:35.079902+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (146, 1, '2115', 'فواتير لم تُستلم (GRNI)', 'liability', NULL, 'active', '2026-04-13 17:07:35.079902', 'Goods Received Not Invoiced', NULL, 3, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-13 17:07:35.079902+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (147, 1, '5110', 'تكلفة البضاعة المباعة', 'expense', NULL, 'active', '2026-04-13 17:07:35.079902', 'Cost of Goods Sold', NULL, 3, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-13 17:07:35.079902+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (148, 1, '5150', 'فروقات جرد', 'expense', NULL, 'active', '2026-04-13 17:07:35.079902', 'Inventory Variance', NULL, 3, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-13 17:07:35.079902+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (149, 1, '5225', 'تكلفة المشاريع (محولة من WIP)', 'expense', NULL, 'active', '2026-04-13 17:07:35.079902', 'Project Cost Transferred', NULL, 3, true, true, 0.00, 0.00, NULL, NULL, NULL, NULL, false, '2026-04-13 17:07:35.079902+00', NULL, NULL, NULL, 'debit');
INSERT INTO public.chart_of_accounts (id, "companyId", code, name, type, "parentCode", status, "createdAt", "nameEn", "parentId", level, "isActive", "allowPosting", "openingBalance", "currentBalance", description, "branchId", "activityType", "costCenter", "isAnalytical", "updatedAt", "deletedAt", subtype, "accountSubtype", nature) VALUES (130, 1, '2100', 'الذمم الدائنة', 'liability', '2000', 'active', '2026-04-11 18:17:23.958805', NULL, NULL, 1, true, true, 0.00, 185000.00, NULL, NULL, NULL, NULL, false, '2026-04-11 18:17:23.958805+00', NULL, NULL, NULL, 'credit');


--
-- Data for Name: job_titles; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (51, 'مدير عام', NULL, 'general', 1, true, '2026-04-12 04:13:39.515559+00', '2026-04-12 04:13:39.515559+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (52, 'مدير قسم', NULL, 'general', 1, true, '2026-04-12 04:13:39.560573+00', '2026-04-12 04:13:39.560573+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (53, 'محاسب', NULL, 'general', 1, true, '2026-04-12 04:13:39.60029+00', '2026-04-12 04:13:39.60029+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (54, 'مهندس برمجيات', NULL, 'general', 1, true, '2026-04-12 04:13:39.638223+00', '2026-04-12 04:13:39.638223+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (55, 'مسؤول موارد بشرية', NULL, 'general', 1, true, '2026-04-12 04:13:39.675229+00', '2026-04-12 04:13:39.675229+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (56, 'مندوب مبيعات', NULL, 'general', 1, true, '2026-04-12 04:13:39.713911+00', '2026-04-12 04:13:39.713911+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (57, 'محلل بيانات', NULL, 'general', 1, true, '2026-04-12 04:13:39.754005+00', '2026-04-12 04:13:39.754005+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (58, 'مستشار قانوني', NULL, 'general', 1, true, '2026-04-12 04:13:39.797184+00', '2026-04-12 04:13:39.797184+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (59, 'مسؤول تسويق', NULL, 'general', 1, true, '2026-04-12 04:13:39.838556+00', '2026-04-12 04:13:39.838556+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (60, 'فني صيانة', NULL, 'general', 1, true, '2026-04-12 04:13:39.878106+00', '2026-04-12 04:13:39.878106+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (61, 'سكرتير', NULL, 'general', 1, true, '2026-04-12 04:13:39.918827+00', '2026-04-12 04:13:39.918827+00');
INSERT INTO public.job_titles (id, name, "nameEn", category, "companyId", "isActive", "createdAt", "updatedAt") VALUES (62, 'مدير مشاريع', NULL, 'general', 1, true, '2026-04-12 04:13:39.959709+00', '2026-04-12 04:13:39.959709+00');


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (148, 'owner', '*', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (149, 'general_manager', '*', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (150, 'hr_manager', 'hr:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (151, 'hr_manager', 'hr:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (152, 'hr_manager', 'hr:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (153, 'hr_manager', 'hr:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (154, 'finance_manager', 'finance:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (155, 'finance_manager', 'finance:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (156, 'finance_manager', 'finance:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (157, 'finance_manager', 'finance:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (158, 'fleet_manager', 'fleet:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (159, 'fleet_manager', 'fleet:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (160, 'fleet_manager', 'fleet:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (161, 'fleet_manager', 'fleet:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (162, 'warehouse_manager', 'warehouse:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (163, 'warehouse_manager', 'warehouse:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (164, 'warehouse_manager', 'warehouse:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (165, 'warehouse_manager', 'warehouse:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (166, 'property_manager', 'property:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (167, 'property_manager', 'property:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (168, 'property_manager', 'property:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (169, 'property_manager', 'property:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (170, 'projects_manager', 'projects:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (171, 'projects_manager', 'projects:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (172, 'projects_manager', 'projects:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (173, 'projects_manager', 'projects:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (174, 'projects_manager', 'operations:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (175, 'projects_manager', 'operations:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (176, 'projects_manager', 'operations:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (177, 'projects_manager', 'operations:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (178, 'legal_manager', 'legal:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (179, 'legal_manager', 'legal:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (180, 'legal_manager', 'legal:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (181, 'legal_manager', 'legal:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (182, 'support_manager', 'support:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (183, 'support_manager', 'support:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (184, 'support_manager', 'support:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (185, 'support_manager', 'support:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (186, 'crm_manager', 'crm:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (187, 'crm_manager', 'crm:create', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (188, 'crm_manager', 'crm:update', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (189, 'crm_manager', 'crm:delete', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (190, 'bi_manager', 'bi:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (191, 'bi_manager', 'reports:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (192, 'branch_manager', 'hr:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (193, 'branch_manager', 'finance:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (194, 'employee', 'hr:read', NULL, '2026-04-11 21:02:22.742033+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (199, 'owner', 'audit:read', NULL, '2026-04-11 22:02:43.763904+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (200, 'general_manager', 'audit:read', NULL, '2026-04-11 22:02:43.763904+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (201, 'hr_manager', 'hr:discipline:read', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (202, 'hr_manager', 'hr:discipline:create', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (203, 'hr_manager', 'hr:discipline:update', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (204, 'general_manager', 'hr:discipline:read', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (205, 'general_manager', 'hr:discipline:approve', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (206, 'owner', 'hr:discipline:read', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (207, 'owner', 'hr:discipline:approve', NULL, '2026-04-13 17:07:34.976653+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (208, 'hr_manager', 'hr:approve', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (209, 'hr_manager', 'hr:discipline:approve', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (210, 'hr_manager', 'documents:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (211, 'hr_manager', 'documents:create', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (212, 'hr_manager', 'documents:download', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (213, 'finance_manager', 'documents:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (214, 'finance_manager', 'documents:download', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (215, 'finance_manager', 'reports:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (216, 'fleet_manager', 'documents:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (217, 'fleet_manager', 'documents:download', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (218, 'legal_manager', 'documents:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (219, 'legal_manager', 'documents:create', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (220, 'legal_manager', 'documents:update', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (221, 'legal_manager', 'documents:delete', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (222, 'legal_manager', 'documents:download', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (223, 'property_manager', 'documents:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (224, 'property_manager', 'documents:download', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (225, 'bi_manager', 'audit:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (226, 'branch_manager', 'fleet:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (227, 'branch_manager', 'warehouse:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (228, 'branch_manager', 'property:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (229, 'branch_manager', 'projects:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (230, 'branch_manager', 'operations:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (231, 'branch_manager', 'legal:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (232, 'branch_manager', 'support:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (233, 'branch_manager', 'crm:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (234, 'branch_manager', 'documents:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (235, 'branch_manager', 'documents:download', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (236, 'branch_manager', 'reports:read', NULL, '2026-04-13 17:07:35.143826+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (237, 'employee', 'hr:self', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (238, 'employee', 'operations:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (239, 'employee', 'operations:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (240, 'employee', 'operations:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (241, 'employee', 'tasks:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (242, 'employee', 'tasks:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (243, 'employee', 'tasks:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (244, 'employee', 'support:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (245, 'employee', 'support:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (246, 'employee', 'documents:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (247, 'employee', 'documents:download', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (248, 'employee', 'notifications:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (249, 'employee', 'notifications:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (250, 'branch_manager', 'hr:self', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (251, 'branch_manager', 'hr:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (252, 'branch_manager', 'hr:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (253, 'branch_manager', 'hr:approve', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (254, 'branch_manager', 'finance:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (255, 'branch_manager', 'finance:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (256, 'branch_manager', 'fleet:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (257, 'branch_manager', 'fleet:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (258, 'branch_manager', 'fleet:delete', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (259, 'branch_manager', 'projects:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (260, 'branch_manager', 'projects:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (261, 'branch_manager', 'warehouse:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (262, 'branch_manager', 'warehouse:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (263, 'branch_manager', 'property:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (264, 'branch_manager', 'property:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (265, 'branch_manager', 'crm:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (266, 'branch_manager', 'crm:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (267, 'branch_manager', 'operations:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (268, 'branch_manager', 'operations:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (269, 'branch_manager', 'tasks:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (270, 'branch_manager', 'tasks:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (271, 'branch_manager', 'tasks:delete', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (272, 'branch_manager', 'support:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (273, 'branch_manager', 'support:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (274, 'branch_manager', 'audit:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (275, 'hr_manager', 'hr:self', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (277, 'hr_manager', 'operations:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (278, 'hr_manager', 'tasks:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (279, 'hr_manager', 'tasks:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (280, 'finance_manager', 'hr:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (281, 'finance_manager', 'fleet:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (282, 'finance_manager', 'warehouse:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (283, 'finance_manager', 'property:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (284, 'finance_manager', 'projects:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (285, 'finance_manager', 'crm:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (286, 'finance_manager', 'audit:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (287, 'support_manager', 'hr:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (288, 'support_manager', 'operations:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (289, 'crm_manager', 'operations:read', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (290, 'crm_manager', 'tasks:create', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (291, 'crm_manager', 'tasks:update', NULL, '2026-04-13 17:07:35.160892+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (292, 'finance_manager', 'finance:approve', NULL, '2026-04-24 00:00:00+00');
INSERT INTO public.role_permissions (id, role, permission, "companyId", "createdAt") VALUES (293, 'branch_manager', 'finance:approve', NULL, '2026-04-24 00:00:00+00');


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: system_settings; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (1, NULL, NULL, 'companyName', '', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (2, NULL, NULL, 'companyNameEn', '', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (3, NULL, NULL, 'currency', 'SAR', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (4, NULL, NULL, 'timezone', 'Asia/Riyadh', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (5, NULL, NULL, 'language', 'ar', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (6, NULL, NULL, 'taxNumber', '', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (7, NULL, NULL, 'crNumber', '', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (8, NULL, NULL, 'phone', '', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (9, NULL, NULL, 'email', '', 'string', '2026-04-09 10:39:36.01156');
INSERT INTO public.system_settings (id, "companyId", "branchId", key, value, "dataType", "updatedAt") VALUES (10, NULL, NULL, 'address', '', 'string', '2026-04-09 10:39:36.01156');


--
-- Name: branches_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.branches_id_seq', 2, true);


--
-- Name: chart_of_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.chart_of_accounts_id_seq', 149, true);


--
-- Name: companies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.companies_id_seq', 1, true);


--
-- Name: job_titles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.job_titles_id_seq', 62, true);


--
-- Name: permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.permissions_id_seq', 1, true);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.role_permissions_id_seq', 291, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.roles_id_seq', 4, true);


--
-- Name: system_settings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.system_settings_id_seq', 10, true);


--
-- PostgreSQL database dump complete
--

\unrestrict 2TH4EZfPNHHlpzq6joygm408RgsP6390ntZGiNHFiYbq6mGYKtGZkjAZ7VqRfy9

