ALTER TABLE branches ADD COLUMN IF NOT EXISTS "logoUrl" TEXT;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS "address" TEXT;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS "taxNumber" VARCHAR(50);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS "crNumber" VARCHAR(50);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS "email" VARCHAR(200);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS "website" VARCHAR(200);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS "footerText" TEXT;
