-- Migration 125: Add missing companyId indexes for multi-tenant query performance
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_alert_fatigue_settings_companyId ON public.alert_fatigue_settings ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_alert_mute_rules_companyId ON public.alert_mute_rules ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_attendance_deductions_companyId ON public.attendance_deductions ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_attendance_policies_companyId ON public.attendance_policies ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_logs_archive_companyId ON public.audit_logs_archive ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_audit_umrah_access_companyId ON public.audit_umrah_access ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bi_dashboards_companyId ON public.bi_dashboards ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bi_kpis_companyId ON public.bi_kpis ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_bi_reports_companyId ON public.bi_reports ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_branches_companyId ON public.branches ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_clients_companyId ON public.clients ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_collection_follow_ups_companyId ON public.collection_follow_ups ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_communications_log_companyId ON public.communications_log ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_crm_contacts_companyId ON public.crm_contacts ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_customer_advances_companyId ON public.customer_advances ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_daily_close_log_companyId ON public.daily_close_log ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_daily_closures_companyId ON public.daily_closures ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_data_retention_policies_companyId ON public.data_retention_policies ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_departments_companyId ON public.departments ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_depreciation_entries_companyId ON public.depreciation_entries ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_digital_signature_otps_companyId ON public.digital_signature_otps ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_document_folders_companyId ON public.document_folders ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_document_templates_companyId ON public.document_templates ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_documents_companyId ON public.documents ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_email_queue_companyId ON public.email_queue ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_commission_calculations_companyId ON public.employee_commission_calculations ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_commission_plans_companyId ON public.employee_commission_plans ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_development_plans_companyId ON public.employee_development_plans ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_kpi_snapshots_companyId ON public.employee_kpi_snapshots ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_monthly_attendance_companyId ON public.employee_monthly_attendance ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_of_month_companyId ON public.employee_of_month ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_salary_components_companyId ON public.employee_salary_components ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_transfers_companyId ON public.employee_transfers ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_evaluation_participants_companyId ON public.evaluation_participants ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fleet_preventive_plans_companyId ON public.fleet_preventive_plans ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fleet_traffic_violations_companyId ON public.fleet_traffic_violations ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_audits_companyId ON public.governance_audits ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_capa_companyId ON public.governance_capa ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_compliance_companyId ON public.governance_compliance ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_policies_companyId ON public.governance_policies ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_risks_companyId ON public.governance_risks ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hr_excuse_requests_companyId ON public.hr_excuse_requests ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hr_exit_clearance_companyId ON public.hr_exit_clearance ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hr_leave_balances_companyId ON public.hr_leave_balances ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hr_leave_types_companyId ON public.hr_leave_types ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_hr_loan_installments_companyId ON public.hr_loan_installments ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_integration_logs_archive_companyId ON public.integration_logs_archive ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_integrations_companyId ON public.integrations ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_inventory_counts_companyId ON public.inventory_counts ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_invoice_collection_stages_companyId ON public.invoice_collection_stages ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_invoice_payments_companyId ON public.invoice_payments ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_job_titles_companyId ON public.job_titles ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_kpi_snapshots_companyId ON public.kpi_snapshots ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_legal_correspondence_companyId ON public.legal_correspondence ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_legal_judgments_companyId ON public.legal_judgments ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_loan_accounts_companyId ON public.loan_accounts ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_maintenance_requests_companyId ON public.maintenance_requests ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_marketing_campaigns_companyId ON public.marketing_campaigns ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_notification_log_companyId ON public.notification_log ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_notification_webhooks_companyId ON public.notification_webhooks ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_notifications_companyId ON public.notifications ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_payment_runs_companyId ON public.payment_runs ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_pbx_calls_companyId ON public.pbx_calls ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_permissions_companyId ON public.permissions ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_policy_module_links_companyId ON public.policy_module_links ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_project_costs_companyId ON public.project_costs ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_project_milestones_companyId ON public.project_milestones ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_project_resources_companyId ON public.project_resources ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_project_risks_companyId ON public.project_risks ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_property_contracts_companyId ON public.property_contracts ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_property_inspections_companyId ON public.property_inspections ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_property_security_deposits_companyId ON public.property_security_deposits ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_public_holidays_companyId ON public.public_holidays ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_purchase_requests_companyId ON public.purchase_requests ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_push_subscriptions_companyId ON public.push_subscriptions ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_request_types_companyId ON public.request_types ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_scheduled_reports_companyId ON public.scheduled_reports ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sla_definitions_companyId ON public.sla_definitions ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_smart_alerts_companyId ON public.smart_alerts ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_sms_queue_companyId ON public.sms_queue ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_stock_transfers_companyId ON public.stock_transfers ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_system_evaluations_companyId ON public.system_evaluations ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_system_settings_companyId ON public.system_settings ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_system_stops_companyId ON public.system_stops ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_technicians_companyId ON public.technicians ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_ticket_csat_ratings_companyId ON public.ticket_csat_ratings ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_agent_invoices_companyId ON public.umrah_agent_invoices ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_import_batches_companyId ON public.umrah_import_batches ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_import_logs_companyId ON public.umrah_import_logs ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_nusk_invoices_companyId ON public.umrah_nusk_invoices ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_packages_companyId ON public.umrah_packages ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_payments_companyId ON public.umrah_payments ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_penalties_companyId ON public.umrah_penalties ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_pricing_companyId ON public.umrah_pricing ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_sales_invoices_companyId ON public.umrah_sales_invoices ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_seasons_companyId ON public.umrah_seasons ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_sub_agents_companyId ON public.umrah_sub_agents ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_transport_companyId ON public.umrah_transport ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_violations_companyId ON public.umrah_violations ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_roles_companyId ON public.user_roles ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_user_shortcuts_companyId ON public.user_shortcuts ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_warehouse_categories_companyId ON public.warehouse_categories ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_whatsapp_queue_companyId ON public.whatsapp_queue ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workflow_definitions_companyId ON public.workflow_definitions ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workflows_companyId ON public.workflows ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_zatca_settings_companyId ON public.zatca_settings ("companyId");
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_attendance_deletedAt ON public.attendance ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_budget_approval_requests_deletedAt ON public.budget_approval_requests ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_business_rules_deletedAt ON public.business_rules ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_chart_of_accounts_deletedAt ON public.chart_of_accounts ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_communications_log_deletedAt ON public.communications_log ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_document_templates_deletedAt ON public.document_templates ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_commission_calculations_deletedAt ON public.employee_commission_calculations ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_commission_plans_deletedAt ON public.employee_commission_plans ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_development_plans_deletedAt ON public.employee_development_plans ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_employee_violations_deletedAt ON public.employee_violations ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_fleet_traffic_violations_deletedAt ON public.fleet_traffic_violations ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_gov_integration_links_deletedAt ON public.gov_integration_links ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_audits_deletedAt ON public.governance_audits ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_compliance_deletedAt ON public.governance_compliance ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_policies_deletedAt ON public.governance_policies ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_governance_risks_deletedAt ON public.governance_risks ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_intercompany_transactions_deletedAt ON public.intercompany_transactions ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_job_applications_deletedAt ON public.job_applications ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_legal_sessions_deletedAt ON public.legal_sessions ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_policy_compliance_actions_deletedAt ON public.policy_compliance_actions ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_property_owners_deletedAt ON public.property_owners ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_public_holidays_deletedAt ON public.public_holidays ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_rental_contracts_deletedAt ON public.rental_contracts ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_training_enrollments_deletedAt ON public.training_enrollments ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_import_batches_deletedAt ON public.umrah_import_batches ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_nusk_invoices_deletedAt ON public.umrah_nusk_invoices ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_packages_deletedAt ON public.umrah_packages ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_payments_deletedAt ON public.umrah_payments ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_pricing_deletedAt ON public.umrah_pricing ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_sales_invoices_deletedAt ON public.umrah_sales_invoices ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_sub_agents_deletedAt ON public.umrah_sub_agents ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_transport_deletedAt ON public.umrah_transport ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_umrah_violations_deletedAt ON public.umrah_violations ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_warehouse_categories_deletedAt ON public.warehouse_categories ("deletedAt") WHERE "deletedAt" IS NULL;
CREATE INDEX CONCURRENTLY IF NOT EXISTS idx_workflow_instances_deletedAt ON public.workflow_instances ("deletedAt") WHERE "deletedAt" IS NULL;
