import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dirname!, "../../../..");
const read = (p: string) => readFileSync(join(REPO_ROOT, p), "utf8");

// ─── Renewal flow contract — claude/hr-driver-integrated-view branch ─────
// Locks the cross-module contract introduced over 22 commits on this
// branch: every duration-tracked artefact (company documents, fleet
// insurance, employee documents, bank guarantees, legal contracts,
// rental contracts, smart expenses) must call registerObligationWithTask
// (NOT just registerObligation) so the calendar entry comes with a
// matching task on the responsible department's queue. The bridge
// helper itself must seed an rbac_user_roles row when none exists,
// and the close-the-loop renew endpoint on company documents must
// post an expense JE + register the next-cycle obligation atomically.

const BRIDGE = read("artifacts/api-server/src/lib/obligationTaskBridge.ts");
const HR = read("artifacts/api-server/src/routes/hr.ts");
const FLEET = read("artifacts/api-server/src/routes/fleet.ts");
const FINANCE_JOURNAL = read("artifacts/api-server/src/routes/finance-journal.ts");
const FINANCE_HARDENING = read("artifacts/api-server/src/routes/finance-hardening.ts");
const LEGAL = read("artifacts/api-server/src/routes/legal.ts");
const PROPERTIES = read("artifacts/api-server/src/routes/properties.ts");
const ENSURE_ROLE = read("artifacts/api-server/src/lib/rbac/ensureRole.ts");

describe("obligationTaskBridge — helper contract", () => {
  it("exports registerObligationWithTask", () => {
    expect(BRIDGE).toMatch(/export\s+async\s+function\s+registerObligationWithTask/);
  });

  it("registers the obligation by delegating to obligationsEngine", () => {
    expect(BRIDGE).toContain('from "./obligationsEngine.js"');
    expect(BRIDGE).toMatch(/await\s+registerObligation\s*\(\s*input\s*\)/);
  });

  it("opens a tasks row with type='renewal' + autoGenerated=true", () => {
    expect(BRIDGE).toContain('INSERT INTO tasks');
    expect(BRIDGE).toContain("'renewal'");
    expect(BRIDGE).toContain("true"); // autoGenerated flag
    expect(BRIDGE).toContain('"linkedEntityType"');
    expect(BRIDGE).toContain('"linkedEntityId"');
  });

  it("is idempotent — skips if a pending/in_progress renewal task already exists", () => {
    expect(BRIDGE).toMatch(/status IN \('pending', 'in_progress'\)/);
  });

  it("resolves assignee from entityType → role fallback map", () => {
    // The map covers the 7 entity types we wired to the bridge.
    expect(BRIDGE).toContain("company_document");
    expect(BRIDGE).toContain("hr_manager");
    expect(BRIDGE).toContain("fleet_vehicle");
    expect(BRIDGE).toContain("fleet_manager");
    expect(BRIDGE).toContain("bank_guarantee");
    expect(BRIDGE).toContain("finance_manager");
    expect(BRIDGE).toContain("legal_contract");
    expect(BRIDGE).toContain("legal_manager");
    expect(BRIDGE).toContain("rental_contract");
    expect(BRIDGE).toContain("property_manager");
    expect(BRIDGE).toContain("employee_document");
    expect(BRIDGE).toContain("expense");
  });

  it("falls back to department manager when responsibleDepartmentId is supplied", () => {
    expect(BRIDGE).toContain("responsibleDepartmentId");
    expect(BRIDGE).toContain("departments d");
    expect(BRIDGE).toContain('d."managerId"');
  });
});

describe("renewal bridge wired into every duration-tracked POST endpoint", () => {
  it("hr.ts /company-documents calls registerObligationWithTask", () => {
    expect(HR).toContain('from "../lib/obligationTaskBridge.js"');
    const idx = HR.indexOf('router.post("/company-documents"');
    expect(idx).toBeGreaterThan(-1);
    // Look at the next ~5000 chars of the handler.
    const block = HR.slice(idx, idx + 5000);
    expect(block).toContain("registerObligationWithTask");
    expect(block).toContain('entityType: "company_document"');
  });

  it("hr.ts /employee-documents calls registerObligationWithTask", () => {
    const idx = HR.indexOf('router.post("/employee-documents"');
    expect(idx).toBeGreaterThan(-1);
    const block = HR.slice(idx, idx + 4000);
    expect(block).toContain("registerObligationWithTask");
    expect(block).toContain('entityType: "employee_document"');
  });

  it("fleet.ts /insurance calls registerObligationWithTask", () => {
    expect(FLEET).toContain('from "../lib/obligationTaskBridge.js"');
    const idx = FLEET.indexOf('router.post("/insurance"');
    expect(idx).toBeGreaterThan(-1);
    // Bumped from 4000 → 8000 because the insurance POST body has a
    // sizeable preamble (date validation, vehicle lookup, GL post)
    // before the renewal-obligation block.
    const block = FLEET.slice(idx, idx + 8000);
    expect(block).toContain("registerObligationWithTask");
    expect(block).toContain('entityType: "fleet_vehicle"');
  });

  it("finance-hardening.ts /bank-guarantees calls registerObligationWithTask", () => {
    expect(FINANCE_HARDENING).toContain('from "../lib/obligationTaskBridge.js"');
    const idx = FINANCE_HARDENING.indexOf('post("/bank-guarantees"');
    expect(idx).toBeGreaterThan(-1);
    const block = FINANCE_HARDENING.slice(idx, idx + 4000);
    expect(block).toContain("registerObligationWithTask");
    expect(block).toContain('entityType: "bank_guarantee"');
  });

  it("legal.ts /contracts calls registerObligationWithTask", () => {
    expect(LEGAL).toContain('from "../lib/obligationTaskBridge.js"');
    const idx = LEGAL.indexOf('router.post("/contracts"');
    expect(idx).toBeGreaterThan(-1);
    // Bumped from 4000 → 8000 — the contract POST has duplicate-ref +
    // date validation + numbering-service + INSERT preamble before the
    // renewal-obligation block.
    const block = LEGAL.slice(idx, idx + 8000);
    expect(block).toContain("registerObligationWithTask");
    expect(block).toContain('entityType: "legal_contract"');
  });

  it("properties.ts rental contracts upgraded to registerObligationWithTask", () => {
    expect(PROPERTIES).toContain('from "../lib/obligationTaskBridge.js"');
    expect(PROPERTIES).toContain('registerObligationWithTask');
  });

  it("finance-journal.ts smart-expense renewal uses the bridge", () => {
    expect(FINANCE_JOURNAL).toContain('from "../lib/obligationTaskBridge.js"');
    // The smart-expense block fires only when coverageEndDate is set.
    expect(FINANCE_JOURNAL).toContain("coverageEndDate");
    expect(FINANCE_JOURNAL).toContain("registerObligationWithTask");
  });
});

describe("close-the-loop renew endpoint — company documents", () => {
  it("hr.ts exposes POST /company-documents/:id/renew", () => {
    expect(HR).toContain('post("/company-documents/:id/renew"');
  });

  it("renew handler shifts expiryDate forward", () => {
    const idx = HR.indexOf('post("/company-documents/:id/renew"');
    expect(idx).toBeGreaterThan(-1);
    const block = HR.slice(idx, idx + 6000);
    expect(block).toContain('UPDATE company_documents');
    expect(block).toContain('"expiryDate" = $1');
  });

  it("renew handler closes the old obligation via markObligationMet", () => {
    const idx = HR.indexOf('post("/company-documents/:id/renew"');
    const block = HR.slice(idx, idx + 6000);
    expect(block).toContain("markObligationMet");
    expect(block).toContain('"company_document"');
    expect(block).toContain('"renewal"');
  });

  it("renew handler posts the optional renewal-fee expense JE", () => {
    const idx = HR.indexOf('post("/company-documents/:id/renew"');
    const block = HR.slice(idx, idx + 6000);
    expect(block).toContain("postJournalEntry");
    expect(block).toContain("postExpense");
    // sourceKey includes the new expiry so the same JE can't post twice.
    expect(block).toContain("company_document_renewal_paid:");
  });

  it("renew handler registers the next-cycle obligation+task", () => {
    const idx = HR.indexOf('post("/company-documents/:id/renew"');
    const block = HR.slice(idx, idx + 6000);
    expect(block).toContain("registerObligationWithTask");
    // The dedupeKey for the new cycle includes the new expiry so the
    // engine creates a fresh row (template literal, not a plain string).
    expect(block).toContain("`company_document:${id}:${b.newExpiryDate}`");
  });
});

describe("ensureRbacRoleByKey — lazy role seed for fresh tenants", () => {
  it("exports ensureRbacRoleByKey", () => {
    expect(ENSURE_ROLE).toMatch(/export\s+async\s+function\s+ensureRbacRoleByKey/);
  });

  it("inserts a system-wide rbac_roles row when none exists", () => {
    expect(ENSURE_ROLE).toContain("INSERT INTO rbac_roles");
    expect(ENSURE_ROLE).toContain("VALUES (NULL,");
    expect(ENSURE_ROLE).toContain("ON CONFLICT DO NOTHING");
  });

  it("covers all role keys seeded by migration 249", () => {
    const keys = ["driver", "accountant", "sales_rep", "cashier", "warehouse_keeper", "supervisor"];
    for (const k of keys) {
      expect(ENSURE_ROLE).toContain(k);
    }
  });

  it("exports getRoleLabel for downstream UI use", () => {
    expect(ENSURE_ROLE).toMatch(/export\s+function\s+getRoleLabel/);
  });
});

describe("employee POST binds new users to rbac_user_roles via ensureRbacRoleByKey", () => {
  it("employees.ts imports ensureRbacRoleByKey", () => {
    const employees = read("artifacts/api-server/src/routes/employees.ts");
    expect(employees).toContain('from "../lib/rbac/ensureRole.js"');
  });

  it("employees POST resolves an effectiveRole then uses it for users.role + rbac_user_roles", () => {
    const employees = read("artifacts/api-server/src/routes/employees.ts");
    // The effectiveRole variable replaces the body.role on both the
    // assignment INSERT, the users INSERT, and the rbac binding.
    expect(employees).toContain("let effectiveRole = role;");
    // assignment INSERT uses effectiveRole
    expect(employees).toMatch(/INSERT INTO employee_assignments[\s\S]{1,400}effectiveRole/);
    // users INSERT uses effectiveRole
    expect(employees).toMatch(/INSERT INTO users[\s\S]{1,400}effectiveRole/);
    // rbac binding uses effectiveRole and the ensure helper
    expect(employees).toContain("ensureRbacRoleByKey");
    expect(employees).toContain("INSERT INTO rbac_user_roles");
  });
});

describe("subsidiary-account integration — single source of truth", () => {
  it("employees POST routes through createSubsidiaryAccountsForEntity (not the hardcoded 1400)", () => {
    const employees = read("artifacts/api-server/src/routes/employees.ts");
    // The new canonical path
    expect(employees).toContain('createSubsidiaryAccountsForEntity(effectiveCompanyId, "employee", empId, name)');
    // The old hardcoded 1400 INSERT must be gone
    expect(employees).not.toMatch(/INSERT INTO subsidiary_accounts[\s\S]{1,300}'employee', \$2, 'custody'/);
  });

  it("clients POST is now atomic (engine call inside withTransaction)", () => {
    const clients = read("artifacts/api-server/src/routes/clients.ts");
    // The fire-and-forget pattern must be gone.
    expect(clients).not.toMatch(/createSubsidiaryAccountsForEntity[\s\S]{1,200}\.catch/);
    // Inside-txn pattern present.
    expect(clients).toContain("await createSubsidiaryAccountsForEntity(scope.companyId");
  });

  it("vendors POST seeds the payable subsidiary atomically", () => {
    const vendors = read("artifacts/api-server/src/routes/finance-vendors.ts");
    expect(vendors).toContain('createSubsidiaryAccountsForEntity(scope.companyId, "vendor"');
    expect(vendors).toContain("withTransaction");
  });
});
